// Code generated by ent, DO NOT EDIT.

package chat

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldID, id))
}

// OwnerAccountID applies equality check predicate on the "owner_account_id" field. It's identical to OwnerAccountIDEQ.
func OwnerAccountID(v uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldOwnerAccountID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldPlatform, v))
}

// ChatID applies equality check predicate on the "chat_id" field. It's identical to ChatIDEQ.
func ChatID(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatID, v))
}

// ChatName applies equality check predicate on the "chat_name" field. It's identical to ChatNameEQ.
func ChatName(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatName, v))
}

// ChatType applies equality check predicate on the "chat_type" field. It's identical to ChatTypeEQ.
func ChatType(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatType, v))
}

// ChatUsername applies equality check predicate on the "chat_username" field. It's identical to ChatUsernameEQ.
func ChatUsername(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatUsername, v))
}

// Note applies equality check predicate on the "note" field. It's identical to NoteEQ.
func Note(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldNote, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldUpdatedAt, v))
}

// OwnerAccountIDEQ applies the EQ predicate on the "owner_account_id" field.
func OwnerAccountIDEQ(v uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDNEQ applies the NEQ predicate on the "owner_account_id" field.
func OwnerAccountIDNEQ(v uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDIn applies the In predicate on the "owner_account_id" field.
func OwnerAccountIDIn(vs ...uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDNotIn applies the NotIn predicate on the "owner_account_id" field.
func OwnerAccountIDNotIn(vs ...uuid.UUID) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldOwnerAccountID, vs...))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldPlatform, v))
}

// ChatIDEQ applies the EQ predicate on the "chat_id" field.
func ChatIDEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatID, v))
}

// ChatIDNEQ applies the NEQ predicate on the "chat_id" field.
func ChatIDNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldChatID, v))
}

// ChatIDIn applies the In predicate on the "chat_id" field.
func ChatIDIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldChatID, vs...))
}

// ChatIDNotIn applies the NotIn predicate on the "chat_id" field.
func ChatIDNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldChatID, vs...))
}

// ChatIDGT applies the GT predicate on the "chat_id" field.
func ChatIDGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldChatID, v))
}

// ChatIDGTE applies the GTE predicate on the "chat_id" field.
func ChatIDGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldChatID, v))
}

// ChatIDLT applies the LT predicate on the "chat_id" field.
func ChatIDLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldChatID, v))
}

// ChatIDLTE applies the LTE predicate on the "chat_id" field.
func ChatIDLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldChatID, v))
}

// ChatIDContains applies the Contains predicate on the "chat_id" field.
func ChatIDContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldChatID, v))
}

// ChatIDHasPrefix applies the HasPrefix predicate on the "chat_id" field.
func ChatIDHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldChatID, v))
}

// ChatIDHasSuffix applies the HasSuffix predicate on the "chat_id" field.
func ChatIDHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldChatID, v))
}

// ChatIDEqualFold applies the EqualFold predicate on the "chat_id" field.
func ChatIDEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldChatID, v))
}

// ChatIDContainsFold applies the ContainsFold predicate on the "chat_id" field.
func ChatIDContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldChatID, v))
}

// ChatNameEQ applies the EQ predicate on the "chat_name" field.
func ChatNameEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatName, v))
}

// ChatNameNEQ applies the NEQ predicate on the "chat_name" field.
func ChatNameNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldChatName, v))
}

// ChatNameIn applies the In predicate on the "chat_name" field.
func ChatNameIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldChatName, vs...))
}

// ChatNameNotIn applies the NotIn predicate on the "chat_name" field.
func ChatNameNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldChatName, vs...))
}

// ChatNameGT applies the GT predicate on the "chat_name" field.
func ChatNameGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldChatName, v))
}

// ChatNameGTE applies the GTE predicate on the "chat_name" field.
func ChatNameGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldChatName, v))
}

// ChatNameLT applies the LT predicate on the "chat_name" field.
func ChatNameLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldChatName, v))
}

// ChatNameLTE applies the LTE predicate on the "chat_name" field.
func ChatNameLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldChatName, v))
}

// ChatNameContains applies the Contains predicate on the "chat_name" field.
func ChatNameContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldChatName, v))
}

// ChatNameHasPrefix applies the HasPrefix predicate on the "chat_name" field.
func ChatNameHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldChatName, v))
}

// ChatNameHasSuffix applies the HasSuffix predicate on the "chat_name" field.
func ChatNameHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldChatName, v))
}

// ChatNameEqualFold applies the EqualFold predicate on the "chat_name" field.
func ChatNameEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldChatName, v))
}

// ChatNameContainsFold applies the ContainsFold predicate on the "chat_name" field.
func ChatNameContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldChatName, v))
}

// ChatTypeEQ applies the EQ predicate on the "chat_type" field.
func ChatTypeEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatType, v))
}

// ChatTypeNEQ applies the NEQ predicate on the "chat_type" field.
func ChatTypeNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldChatType, v))
}

// ChatTypeIn applies the In predicate on the "chat_type" field.
func ChatTypeIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldChatType, vs...))
}

// ChatTypeNotIn applies the NotIn predicate on the "chat_type" field.
func ChatTypeNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldChatType, vs...))
}

// ChatTypeGT applies the GT predicate on the "chat_type" field.
func ChatTypeGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldChatType, v))
}

// ChatTypeGTE applies the GTE predicate on the "chat_type" field.
func ChatTypeGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldChatType, v))
}

// ChatTypeLT applies the LT predicate on the "chat_type" field.
func ChatTypeLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldChatType, v))
}

// ChatTypeLTE applies the LTE predicate on the "chat_type" field.
func ChatTypeLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldChatType, v))
}

// ChatTypeContains applies the Contains predicate on the "chat_type" field.
func ChatTypeContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldChatType, v))
}

// ChatTypeHasPrefix applies the HasPrefix predicate on the "chat_type" field.
func ChatTypeHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldChatType, v))
}

// ChatTypeHasSuffix applies the HasSuffix predicate on the "chat_type" field.
func ChatTypeHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldChatType, v))
}

// ChatTypeEqualFold applies the EqualFold predicate on the "chat_type" field.
func ChatTypeEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldChatType, v))
}

// ChatTypeContainsFold applies the ContainsFold predicate on the "chat_type" field.
func ChatTypeContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldChatType, v))
}

// ChatUsernameEQ applies the EQ predicate on the "chat_username" field.
func ChatUsernameEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldChatUsername, v))
}

// ChatUsernameNEQ applies the NEQ predicate on the "chat_username" field.
func ChatUsernameNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldChatUsername, v))
}

// ChatUsernameIn applies the In predicate on the "chat_username" field.
func ChatUsernameIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldChatUsername, vs...))
}

// ChatUsernameNotIn applies the NotIn predicate on the "chat_username" field.
func ChatUsernameNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldChatUsername, vs...))
}

// ChatUsernameGT applies the GT predicate on the "chat_username" field.
func ChatUsernameGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldChatUsername, v))
}

// ChatUsernameGTE applies the GTE predicate on the "chat_username" field.
func ChatUsernameGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldChatUsername, v))
}

// ChatUsernameLT applies the LT predicate on the "chat_username" field.
func ChatUsernameLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldChatUsername, v))
}

// ChatUsernameLTE applies the LTE predicate on the "chat_username" field.
func ChatUsernameLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldChatUsername, v))
}

// ChatUsernameContains applies the Contains predicate on the "chat_username" field.
func ChatUsernameContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldChatUsername, v))
}

// ChatUsernameHasPrefix applies the HasPrefix predicate on the "chat_username" field.
func ChatUsernameHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldChatUsername, v))
}

// ChatUsernameHasSuffix applies the HasSuffix predicate on the "chat_username" field.
func ChatUsernameHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldChatUsername, v))
}

// ChatUsernameIsNil applies the IsNil predicate on the "chat_username" field.
func ChatUsernameIsNil() predicate.Chat {
	return predicate.Chat(sql.FieldIsNull(FieldChatUsername))
}

// ChatUsernameNotNil applies the NotNil predicate on the "chat_username" field.
func ChatUsernameNotNil() predicate.Chat {
	return predicate.Chat(sql.FieldNotNull(FieldChatUsername))
}

// ChatUsernameEqualFold applies the EqualFold predicate on the "chat_username" field.
func ChatUsernameEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldChatUsername, v))
}

// ChatUsernameContainsFold applies the ContainsFold predicate on the "chat_username" field.
func ChatUsernameContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldChatUsername, v))
}

// NoteEQ applies the EQ predicate on the "note" field.
func NoteEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldNote, v))
}

// NoteNEQ applies the NEQ predicate on the "note" field.
func NoteNEQ(v string) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldNote, v))
}

// NoteIn applies the In predicate on the "note" field.
func NoteIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldNote, vs...))
}

// NoteNotIn applies the NotIn predicate on the "note" field.
func NoteNotIn(vs ...string) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldNote, vs...))
}

// NoteGT applies the GT predicate on the "note" field.
func NoteGT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldNote, v))
}

// NoteGTE applies the GTE predicate on the "note" field.
func NoteGTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldNote, v))
}

// NoteLT applies the LT predicate on the "note" field.
func NoteLT(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldNote, v))
}

// NoteLTE applies the LTE predicate on the "note" field.
func NoteLTE(v string) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldNote, v))
}

// NoteContains applies the Contains predicate on the "note" field.
func NoteContains(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContains(FieldNote, v))
}

// NoteHasPrefix applies the HasPrefix predicate on the "note" field.
func NoteHasPrefix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasPrefix(FieldNote, v))
}

// NoteHasSuffix applies the HasSuffix predicate on the "note" field.
func NoteHasSuffix(v string) predicate.Chat {
	return predicate.Chat(sql.FieldHasSuffix(FieldNote, v))
}

// NoteEqualFold applies the EqualFold predicate on the "note" field.
func NoteEqualFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldEqualFold(FieldNote, v))
}

// NoteContainsFold applies the ContainsFold predicate on the "note" field.
func NoteContainsFold(v string) predicate.Chat {
	return predicate.Chat(sql.FieldContainsFold(FieldNote, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Chat {
	return predicate.Chat(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Chat {
	return predicate.Chat(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Chat {
	return predicate.Chat(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Account) predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Chat {
	return predicate.Chat(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Chat) predicate.Chat {
	return predicate.Chat(sql.NotPredicates(p))
}
