// Code generated by ent, DO NOT EDIT.

package account

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldID, id))
}

// Phone applies equality check predicate on the "phone" field. It's identical to PhoneEQ.
func Phone(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPhone, v))
}

// SessionData applies equality check predicate on the "session_data" field. It's identical to SessionDataEQ.
func SessionData(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSessionData, v))
}

// Pts applies equality check predicate on the "pts" field. It's identical to PtsEQ.
func Pts(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPts, v))
}

// Qts applies equality check predicate on the "qts" field. It's identical to QtsEQ.
func Qts(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldQts, v))
}

// Seq applies equality check predicate on the "seq" field. It's identical to SeqEQ.
func Seq(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSeq, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDate, v))
}

// LastSyncAt applies equality check predicate on the "last_sync_at" field. It's identical to LastSyncAtEQ.
func LastSyncAt(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastSyncAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// PhoneEQ applies the EQ predicate on the "phone" field.
func PhoneEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPhone, v))
}

// PhoneNEQ applies the NEQ predicate on the "phone" field.
func PhoneNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldPhone, v))
}

// PhoneIn applies the In predicate on the "phone" field.
func PhoneIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldPhone, vs...))
}

// PhoneNotIn applies the NotIn predicate on the "phone" field.
func PhoneNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldPhone, vs...))
}

// PhoneGT applies the GT predicate on the "phone" field.
func PhoneGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldPhone, v))
}

// PhoneGTE applies the GTE predicate on the "phone" field.
func PhoneGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldPhone, v))
}

// PhoneLT applies the LT predicate on the "phone" field.
func PhoneLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldPhone, v))
}

// PhoneLTE applies the LTE predicate on the "phone" field.
func PhoneLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldPhone, v))
}

// PhoneContains applies the Contains predicate on the "phone" field.
func PhoneContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldPhone, v))
}

// PhoneHasPrefix applies the HasPrefix predicate on the "phone" field.
func PhoneHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldPhone, v))
}

// PhoneHasSuffix applies the HasSuffix predicate on the "phone" field.
func PhoneHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldPhone, v))
}

// PhoneEqualFold applies the EqualFold predicate on the "phone" field.
func PhoneEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldPhone, v))
}

// PhoneContainsFold applies the ContainsFold predicate on the "phone" field.
func PhoneContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldPhone, v))
}

// SessionDataEQ applies the EQ predicate on the "session_data" field.
func SessionDataEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSessionData, v))
}

// SessionDataNEQ applies the NEQ predicate on the "session_data" field.
func SessionDataNEQ(v string) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSessionData, v))
}

// SessionDataIn applies the In predicate on the "session_data" field.
func SessionDataIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSessionData, vs...))
}

// SessionDataNotIn applies the NotIn predicate on the "session_data" field.
func SessionDataNotIn(vs ...string) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSessionData, vs...))
}

// SessionDataGT applies the GT predicate on the "session_data" field.
func SessionDataGT(v string) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSessionData, v))
}

// SessionDataGTE applies the GTE predicate on the "session_data" field.
func SessionDataGTE(v string) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSessionData, v))
}

// SessionDataLT applies the LT predicate on the "session_data" field.
func SessionDataLT(v string) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSessionData, v))
}

// SessionDataLTE applies the LTE predicate on the "session_data" field.
func SessionDataLTE(v string) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSessionData, v))
}

// SessionDataContains applies the Contains predicate on the "session_data" field.
func SessionDataContains(v string) predicate.Account {
	return predicate.Account(sql.FieldContains(FieldSessionData, v))
}

// SessionDataHasPrefix applies the HasPrefix predicate on the "session_data" field.
func SessionDataHasPrefix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasPrefix(FieldSessionData, v))
}

// SessionDataHasSuffix applies the HasSuffix predicate on the "session_data" field.
func SessionDataHasSuffix(v string) predicate.Account {
	return predicate.Account(sql.FieldHasSuffix(FieldSessionData, v))
}

// SessionDataEqualFold applies the EqualFold predicate on the "session_data" field.
func SessionDataEqualFold(v string) predicate.Account {
	return predicate.Account(sql.FieldEqualFold(FieldSessionData, v))
}

// SessionDataContainsFold applies the ContainsFold predicate on the "session_data" field.
func SessionDataContainsFold(v string) predicate.Account {
	return predicate.Account(sql.FieldContainsFold(FieldSessionData, v))
}

// SettingsIsNil applies the IsNil predicate on the "settings" field.
func SettingsIsNil() predicate.Account {
	return predicate.Account(sql.FieldIsNull(FieldSettings))
}

// SettingsNotNil applies the NotNil predicate on the "settings" field.
func SettingsNotNil() predicate.Account {
	return predicate.Account(sql.FieldNotNull(FieldSettings))
}

// PtsEQ applies the EQ predicate on the "pts" field.
func PtsEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldPts, v))
}

// PtsNEQ applies the NEQ predicate on the "pts" field.
func PtsNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldPts, v))
}

// PtsIn applies the In predicate on the "pts" field.
func PtsIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldPts, vs...))
}

// PtsNotIn applies the NotIn predicate on the "pts" field.
func PtsNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldPts, vs...))
}

// PtsGT applies the GT predicate on the "pts" field.
func PtsGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldPts, v))
}

// PtsGTE applies the GTE predicate on the "pts" field.
func PtsGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldPts, v))
}

// PtsLT applies the LT predicate on the "pts" field.
func PtsLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldPts, v))
}

// PtsLTE applies the LTE predicate on the "pts" field.
func PtsLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldPts, v))
}

// QtsEQ applies the EQ predicate on the "qts" field.
func QtsEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldQts, v))
}

// QtsNEQ applies the NEQ predicate on the "qts" field.
func QtsNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldQts, v))
}

// QtsIn applies the In predicate on the "qts" field.
func QtsIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldQts, vs...))
}

// QtsNotIn applies the NotIn predicate on the "qts" field.
func QtsNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldQts, vs...))
}

// QtsGT applies the GT predicate on the "qts" field.
func QtsGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldQts, v))
}

// QtsGTE applies the GTE predicate on the "qts" field.
func QtsGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldQts, v))
}

// QtsLT applies the LT predicate on the "qts" field.
func QtsLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldQts, v))
}

// QtsLTE applies the LTE predicate on the "qts" field.
func QtsLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldQts, v))
}

// SeqEQ applies the EQ predicate on the "seq" field.
func SeqEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldSeq, v))
}

// SeqNEQ applies the NEQ predicate on the "seq" field.
func SeqNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldSeq, v))
}

// SeqIn applies the In predicate on the "seq" field.
func SeqIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldSeq, vs...))
}

// SeqNotIn applies the NotIn predicate on the "seq" field.
func SeqNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldSeq, vs...))
}

// SeqGT applies the GT predicate on the "seq" field.
func SeqGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldSeq, v))
}

// SeqGTE applies the GTE predicate on the "seq" field.
func SeqGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldSeq, v))
}

// SeqLT applies the LT predicate on the "seq" field.
func SeqLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldSeq, v))
}

// SeqLTE applies the LTE predicate on the "seq" field.
func SeqLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldSeq, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v int) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...int) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v int) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v int) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v int) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v int) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldDate, v))
}

// LastSyncAtEQ applies the EQ predicate on the "last_sync_at" field.
func LastSyncAtEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldLastSyncAt, v))
}

// LastSyncAtNEQ applies the NEQ predicate on the "last_sync_at" field.
func LastSyncAtNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldLastSyncAt, v))
}

// LastSyncAtIn applies the In predicate on the "last_sync_at" field.
func LastSyncAtIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldLastSyncAt, vs...))
}

// LastSyncAtNotIn applies the NotIn predicate on the "last_sync_at" field.
func LastSyncAtNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldLastSyncAt, vs...))
}

// LastSyncAtGT applies the GT predicate on the "last_sync_at" field.
func LastSyncAtGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldLastSyncAt, v))
}

// LastSyncAtGTE applies the GTE predicate on the "last_sync_at" field.
func LastSyncAtGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldLastSyncAt, v))
}

// LastSyncAtLT applies the LT predicate on the "last_sync_at" field.
func LastSyncAtLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldLastSyncAt, v))
}

// LastSyncAtLTE applies the LTE predicate on the "last_sync_at" field.
func LastSyncAtLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldLastSyncAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Account {
	return predicate.Account(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Account {
	return predicate.Account(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Account {
	return predicate.Account(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Account {
	return predicate.Account(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Account {
	return predicate.Account(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasMessages applies the HasEdge predicate on the "messages" edge.
func HasMessages() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, MessagesTable, MessagesColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasMessagesWith applies the HasEdge predicate on the "messages" edge with a given conditions (other predicates).
func HasMessagesWith(preds ...predicate.Message) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newMessagesStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChats applies the HasEdge predicate on the "chats" edge.
func HasChats() predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ChatsTable, ChatsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatsWith applies the HasEdge predicate on the "chats" edge with a given conditions (other predicates).
func HasChatsWith(preds ...predicate.Chat) predicate.Account {
	return predicate.Account(func(s *sql.Selector) {
		step := newChatsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Account) predicate.Account {
	return predicate.Account(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Account) predicate.Account {
	return predicate.Account(sql.NotPredicates(p))
}
