// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
	"github.com/groupultra/telegram-search/ent/predicate"
	"github.com/groupultra/telegram-search/ent/schema"
)

// AccountUpdate is the builder for updating Account entities.
type AccountUpdate struct {
	config
	hooks    []Hook
	mutation *AccountMutation
}

// Where appends a list predicates to the AccountUpdate builder.
func (au *AccountUpdate) Where(ps ...predicate.Account) *AccountUpdate {
	au.mutation.Where(ps...)
	return au
}

// SetPhone sets the "phone" field.
func (au *AccountUpdate) SetPhone(s string) *AccountUpdate {
	au.mutation.SetPhone(s)
	return au
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePhone(s *string) *AccountUpdate {
	if s != nil {
		au.SetPhone(*s)
	}
	return au
}

// SetSessionData sets the "session_data" field.
func (au *AccountUpdate) SetSessionData(s string) *AccountUpdate {
	au.mutation.SetSessionData(s)
	return au
}

// SetNillableSessionData sets the "session_data" field if the given value is not nil.
func (au *AccountUpdate) SetNillableSessionData(s *string) *AccountUpdate {
	if s != nil {
		au.SetSessionData(*s)
	}
	return au
}

// SetSettings sets the "settings" field.
func (au *AccountUpdate) SetSettings(ss *schema.AccountSettings) *AccountUpdate {
	au.mutation.SetSettings(ss)
	return au
}

// ClearSettings clears the value of the "settings" field.
func (au *AccountUpdate) ClearSettings() *AccountUpdate {
	au.mutation.ClearSettings()
	return au
}

// SetPts sets the "pts" field.
func (au *AccountUpdate) SetPts(i int) *AccountUpdate {
	au.mutation.ResetPts()
	au.mutation.SetPts(i)
	return au
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (au *AccountUpdate) SetNillablePts(i *int) *AccountUpdate {
	if i != nil {
		au.SetPts(*i)
	}
	return au
}

// AddPts adds i to the "pts" field.
func (au *AccountUpdate) AddPts(i int) *AccountUpdate {
	au.mutation.AddPts(i)
	return au
}

// SetQts sets the "qts" field.
func (au *AccountUpdate) SetQts(i int) *AccountUpdate {
	au.mutation.ResetQts()
	au.mutation.SetQts(i)
	return au
}

// SetNillableQts sets the "qts" field if the given value is not nil.
func (au *AccountUpdate) SetNillableQts(i *int) *AccountUpdate {
	if i != nil {
		au.SetQts(*i)
	}
	return au
}

// AddQts adds i to the "qts" field.
func (au *AccountUpdate) AddQts(i int) *AccountUpdate {
	au.mutation.AddQts(i)
	return au
}

// SetSeq sets the "seq" field.
func (au *AccountUpdate) SetSeq(i int) *AccountUpdate {
	au.mutation.ResetSeq()
	au.mutation.SetSeq(i)
	return au
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (au *AccountUpdate) SetNillableSeq(i *int) *AccountUpdate {
	if i != nil {
		au.SetSeq(*i)
	}
	return au
}

// AddSeq adds i to the "seq" field.
func (au *AccountUpdate) AddSeq(i int) *AccountUpdate {
	au.mutation.AddSeq(i)
	return au
}

// SetDate sets the "date" field.
func (au *AccountUpdate) SetDate(i int) *AccountUpdate {
	au.mutation.ResetDate()
	au.mutation.SetDate(i)
	return au
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (au *AccountUpdate) SetNillableDate(i *int) *AccountUpdate {
	if i != nil {
		au.SetDate(*i)
	}
	return au
}

// AddDate adds i to the "date" field.
func (au *AccountUpdate) AddDate(i int) *AccountUpdate {
	au.mutation.AddDate(i)
	return au
}

// SetLastSyncAt sets the "last_sync_at" field.
func (au *AccountUpdate) SetLastSyncAt(i int64) *AccountUpdate {
	au.mutation.ResetLastSyncAt()
	au.mutation.SetLastSyncAt(i)
	return au
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (au *AccountUpdate) SetNillableLastSyncAt(i *int64) *AccountUpdate {
	if i != nil {
		au.SetLastSyncAt(*i)
	}
	return au
}

// AddLastSyncAt adds i to the "last_sync_at" field.
func (au *AccountUpdate) AddLastSyncAt(i int64) *AccountUpdate {
	au.mutation.AddLastSyncAt(i)
	return au
}

// SetUpdatedAt sets the "updated_at" field.
func (au *AccountUpdate) SetUpdatedAt(i int64) *AccountUpdate {
	au.mutation.ResetUpdatedAt()
	au.mutation.SetUpdatedAt(i)
	return au
}

// AddUpdatedAt adds i to the "updated_at" field.
func (au *AccountUpdate) AddUpdatedAt(i int64) *AccountUpdate {
	au.mutation.AddUpdatedAt(i)
	return au
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (au *AccountUpdate) AddMessageIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.AddMessageIDs(ids...)
	return au
}

// AddMessages adds the "messages" edges to the Message entity.
func (au *AccountUpdate) AddMessages(m ...*Message) *AccountUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.AddMessageIDs(ids...)
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (au *AccountUpdate) AddChatIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.AddChatIDs(ids...)
	return au
}

// AddChats adds the "chats" edges to the Chat entity.
func (au *AccountUpdate) AddChats(c ...*Chat) *AccountUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.AddChatIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (au *AccountUpdate) Mutation() *AccountMutation {
	return au.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (au *AccountUpdate) ClearMessages() *AccountUpdate {
	au.mutation.ClearMessages()
	return au
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (au *AccountUpdate) RemoveMessageIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.RemoveMessageIDs(ids...)
	return au
}

// RemoveMessages removes "messages" edges to Message entities.
func (au *AccountUpdate) RemoveMessages(m ...*Message) *AccountUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return au.RemoveMessageIDs(ids...)
}

// ClearChats clears all "chats" edges to the Chat entity.
func (au *AccountUpdate) ClearChats() *AccountUpdate {
	au.mutation.ClearChats()
	return au
}

// RemoveChatIDs removes the "chats" edge to Chat entities by IDs.
func (au *AccountUpdate) RemoveChatIDs(ids ...uuid.UUID) *AccountUpdate {
	au.mutation.RemoveChatIDs(ids...)
	return au
}

// RemoveChats removes "chats" edges to Chat entities.
func (au *AccountUpdate) RemoveChats(c ...*Chat) *AccountUpdate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return au.RemoveChatIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (au *AccountUpdate) Save(ctx context.Context) (int, error) {
	au.defaults()
	return withHooks(ctx, au.sqlSave, au.mutation, au.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (au *AccountUpdate) SaveX(ctx context.Context) int {
	affected, err := au.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (au *AccountUpdate) Exec(ctx context.Context) error {
	_, err := au.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (au *AccountUpdate) ExecX(ctx context.Context) {
	if err := au.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (au *AccountUpdate) defaults() {
	if _, ok := au.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		au.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (au *AccountUpdate) check() error {
	if v, ok := au.mutation.Phone(); ok {
		if err := account.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Account.phone": %w`, err)}
		}
	}
	return nil
}

func (au *AccountUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := au.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	if ps := au.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := au.mutation.Phone(); ok {
		_spec.SetField(account.FieldPhone, field.TypeString, value)
	}
	if value, ok := au.mutation.SessionData(); ok {
		_spec.SetField(account.FieldSessionData, field.TypeString, value)
	}
	if value, ok := au.mutation.Settings(); ok {
		_spec.SetField(account.FieldSettings, field.TypeJSON, value)
	}
	if au.mutation.SettingsCleared() {
		_spec.ClearField(account.FieldSettings, field.TypeJSON)
	}
	if value, ok := au.mutation.Pts(); ok {
		_spec.SetField(account.FieldPts, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedPts(); ok {
		_spec.AddField(account.FieldPts, field.TypeInt, value)
	}
	if value, ok := au.mutation.Qts(); ok {
		_spec.SetField(account.FieldQts, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedQts(); ok {
		_spec.AddField(account.FieldQts, field.TypeInt, value)
	}
	if value, ok := au.mutation.Seq(); ok {
		_spec.SetField(account.FieldSeq, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedSeq(); ok {
		_spec.AddField(account.FieldSeq, field.TypeInt, value)
	}
	if value, ok := au.mutation.Date(); ok {
		_spec.SetField(account.FieldDate, field.TypeInt, value)
	}
	if value, ok := au.mutation.AddedDate(); ok {
		_spec.AddField(account.FieldDate, field.TypeInt, value)
	}
	if value, ok := au.mutation.LastSyncAt(); ok {
		_spec.SetField(account.FieldLastSyncAt, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedLastSyncAt(); ok {
		_spec.AddField(account.FieldLastSyncAt, field.TypeInt64, value)
	}
	if value, ok := au.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := au.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(account.FieldUpdatedAt, field.TypeInt64, value)
	}
	if au.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !au.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if au.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.RemovedChatsIDs(); len(nodes) > 0 && !au.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := au.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, au.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	au.mutation.done = true
	return n, nil
}

// AccountUpdateOne is the builder for updating a single Account entity.
type AccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountMutation
}

// SetPhone sets the "phone" field.
func (auo *AccountUpdateOne) SetPhone(s string) *AccountUpdateOne {
	auo.mutation.SetPhone(s)
	return auo
}

// SetNillablePhone sets the "phone" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePhone(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetPhone(*s)
	}
	return auo
}

// SetSessionData sets the "session_data" field.
func (auo *AccountUpdateOne) SetSessionData(s string) *AccountUpdateOne {
	auo.mutation.SetSessionData(s)
	return auo
}

// SetNillableSessionData sets the "session_data" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableSessionData(s *string) *AccountUpdateOne {
	if s != nil {
		auo.SetSessionData(*s)
	}
	return auo
}

// SetSettings sets the "settings" field.
func (auo *AccountUpdateOne) SetSettings(ss *schema.AccountSettings) *AccountUpdateOne {
	auo.mutation.SetSettings(ss)
	return auo
}

// ClearSettings clears the value of the "settings" field.
func (auo *AccountUpdateOne) ClearSettings() *AccountUpdateOne {
	auo.mutation.ClearSettings()
	return auo
}

// SetPts sets the "pts" field.
func (auo *AccountUpdateOne) SetPts(i int) *AccountUpdateOne {
	auo.mutation.ResetPts()
	auo.mutation.SetPts(i)
	return auo
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillablePts(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetPts(*i)
	}
	return auo
}

// AddPts adds i to the "pts" field.
func (auo *AccountUpdateOne) AddPts(i int) *AccountUpdateOne {
	auo.mutation.AddPts(i)
	return auo
}

// SetQts sets the "qts" field.
func (auo *AccountUpdateOne) SetQts(i int) *AccountUpdateOne {
	auo.mutation.ResetQts()
	auo.mutation.SetQts(i)
	return auo
}

// SetNillableQts sets the "qts" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableQts(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetQts(*i)
	}
	return auo
}

// AddQts adds i to the "qts" field.
func (auo *AccountUpdateOne) AddQts(i int) *AccountUpdateOne {
	auo.mutation.AddQts(i)
	return auo
}

// SetSeq sets the "seq" field.
func (auo *AccountUpdateOne) SetSeq(i int) *AccountUpdateOne {
	auo.mutation.ResetSeq()
	auo.mutation.SetSeq(i)
	return auo
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableSeq(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetSeq(*i)
	}
	return auo
}

// AddSeq adds i to the "seq" field.
func (auo *AccountUpdateOne) AddSeq(i int) *AccountUpdateOne {
	auo.mutation.AddSeq(i)
	return auo
}

// SetDate sets the "date" field.
func (auo *AccountUpdateOne) SetDate(i int) *AccountUpdateOne {
	auo.mutation.ResetDate()
	auo.mutation.SetDate(i)
	return auo
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableDate(i *int) *AccountUpdateOne {
	if i != nil {
		auo.SetDate(*i)
	}
	return auo
}

// AddDate adds i to the "date" field.
func (auo *AccountUpdateOne) AddDate(i int) *AccountUpdateOne {
	auo.mutation.AddDate(i)
	return auo
}

// SetLastSyncAt sets the "last_sync_at" field.
func (auo *AccountUpdateOne) SetLastSyncAt(i int64) *AccountUpdateOne {
	auo.mutation.ResetLastSyncAt()
	auo.mutation.SetLastSyncAt(i)
	return auo
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (auo *AccountUpdateOne) SetNillableLastSyncAt(i *int64) *AccountUpdateOne {
	if i != nil {
		auo.SetLastSyncAt(*i)
	}
	return auo
}

// AddLastSyncAt adds i to the "last_sync_at" field.
func (auo *AccountUpdateOne) AddLastSyncAt(i int64) *AccountUpdateOne {
	auo.mutation.AddLastSyncAt(i)
	return auo
}

// SetUpdatedAt sets the "updated_at" field.
func (auo *AccountUpdateOne) SetUpdatedAt(i int64) *AccountUpdateOne {
	auo.mutation.ResetUpdatedAt()
	auo.mutation.SetUpdatedAt(i)
	return auo
}

// AddUpdatedAt adds i to the "updated_at" field.
func (auo *AccountUpdateOne) AddUpdatedAt(i int64) *AccountUpdateOne {
	auo.mutation.AddUpdatedAt(i)
	return auo
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (auo *AccountUpdateOne) AddMessageIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.AddMessageIDs(ids...)
	return auo
}

// AddMessages adds the "messages" edges to the Message entity.
func (auo *AccountUpdateOne) AddMessages(m ...*Message) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.AddMessageIDs(ids...)
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (auo *AccountUpdateOne) AddChatIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.AddChatIDs(ids...)
	return auo
}

// AddChats adds the "chats" edges to the Chat entity.
func (auo *AccountUpdateOne) AddChats(c ...*Chat) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.AddChatIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (auo *AccountUpdateOne) Mutation() *AccountMutation {
	return auo.mutation
}

// ClearMessages clears all "messages" edges to the Message entity.
func (auo *AccountUpdateOne) ClearMessages() *AccountUpdateOne {
	auo.mutation.ClearMessages()
	return auo
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (auo *AccountUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.RemoveMessageIDs(ids...)
	return auo
}

// RemoveMessages removes "messages" edges to Message entities.
func (auo *AccountUpdateOne) RemoveMessages(m ...*Message) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return auo.RemoveMessageIDs(ids...)
}

// ClearChats clears all "chats" edges to the Chat entity.
func (auo *AccountUpdateOne) ClearChats() *AccountUpdateOne {
	auo.mutation.ClearChats()
	return auo
}

// RemoveChatIDs removes the "chats" edge to Chat entities by IDs.
func (auo *AccountUpdateOne) RemoveChatIDs(ids ...uuid.UUID) *AccountUpdateOne {
	auo.mutation.RemoveChatIDs(ids...)
	return auo
}

// RemoveChats removes "chats" edges to Chat entities.
func (auo *AccountUpdateOne) RemoveChats(c ...*Chat) *AccountUpdateOne {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return auo.RemoveChatIDs(ids...)
}

// Where appends a list predicates to the AccountUpdate builder.
func (auo *AccountUpdateOne) Where(ps ...predicate.Account) *AccountUpdateOne {
	auo.mutation.Where(ps...)
	return auo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (auo *AccountUpdateOne) Select(field string, fields ...string) *AccountUpdateOne {
	auo.fields = append([]string{field}, fields...)
	return auo
}

// Save executes the query and returns the updated Account entity.
func (auo *AccountUpdateOne) Save(ctx context.Context) (*Account, error) {
	auo.defaults()
	return withHooks(ctx, auo.sqlSave, auo.mutation, auo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (auo *AccountUpdateOne) SaveX(ctx context.Context) *Account {
	node, err := auo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (auo *AccountUpdateOne) Exec(ctx context.Context) error {
	_, err := auo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (auo *AccountUpdateOne) ExecX(ctx context.Context) {
	if err := auo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (auo *AccountUpdateOne) defaults() {
	if _, ok := auo.mutation.UpdatedAt(); !ok {
		v := account.UpdateDefaultUpdatedAt()
		auo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (auo *AccountUpdateOne) check() error {
	if v, ok := auo.mutation.Phone(); ok {
		if err := account.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Account.phone": %w`, err)}
		}
	}
	return nil
}

func (auo *AccountUpdateOne) sqlSave(ctx context.Context) (_node *Account, err error) {
	if err := auo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(account.Table, account.Columns, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	id, ok := auo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Account.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := auo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, account.FieldID)
		for _, f := range fields {
			if !account.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != account.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := auo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := auo.mutation.Phone(); ok {
		_spec.SetField(account.FieldPhone, field.TypeString, value)
	}
	if value, ok := auo.mutation.SessionData(); ok {
		_spec.SetField(account.FieldSessionData, field.TypeString, value)
	}
	if value, ok := auo.mutation.Settings(); ok {
		_spec.SetField(account.FieldSettings, field.TypeJSON, value)
	}
	if auo.mutation.SettingsCleared() {
		_spec.ClearField(account.FieldSettings, field.TypeJSON)
	}
	if value, ok := auo.mutation.Pts(); ok {
		_spec.SetField(account.FieldPts, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedPts(); ok {
		_spec.AddField(account.FieldPts, field.TypeInt, value)
	}
	if value, ok := auo.mutation.Qts(); ok {
		_spec.SetField(account.FieldQts, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedQts(); ok {
		_spec.AddField(account.FieldQts, field.TypeInt, value)
	}
	if value, ok := auo.mutation.Seq(); ok {
		_spec.SetField(account.FieldSeq, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedSeq(); ok {
		_spec.AddField(account.FieldSeq, field.TypeInt, value)
	}
	if value, ok := auo.mutation.Date(); ok {
		_spec.SetField(account.FieldDate, field.TypeInt, value)
	}
	if value, ok := auo.mutation.AddedDate(); ok {
		_spec.AddField(account.FieldDate, field.TypeInt, value)
	}
	if value, ok := auo.mutation.LastSyncAt(); ok {
		_spec.SetField(account.FieldLastSyncAt, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedLastSyncAt(); ok {
		_spec.AddField(account.FieldLastSyncAt, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := auo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(account.FieldUpdatedAt, field.TypeInt64, value)
	}
	if auo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !auo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if auo.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.RemovedChatsIDs(); len(nodes) > 0 && !auo.mutation.ChatsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := auo.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Account{config: auo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, auo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{account.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	auo.mutation.done = true
	return _node, nil
}
