// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
	"github.com/groupultra/telegram-search/ent/schema"
)

// AccountCreate is the builder for creating a Account entity.
type AccountCreate struct {
	config
	mutation *AccountMutation
	hooks    []Hook
}

// SetPhone sets the "phone" field.
func (ac *AccountCreate) SetPhone(s string) *AccountCreate {
	ac.mutation.SetPhone(s)
	return ac
}

// SetSessionData sets the "session_data" field.
func (ac *AccountCreate) SetSessionData(s string) *AccountCreate {
	ac.mutation.SetSessionData(s)
	return ac
}

// SetNillableSessionData sets the "session_data" field if the given value is not nil.
func (ac *AccountCreate) SetNillableSessionData(s *string) *AccountCreate {
	if s != nil {
		ac.SetSessionData(*s)
	}
	return ac
}

// SetSettings sets the "settings" field.
func (ac *AccountCreate) SetSettings(ss *schema.AccountSettings) *AccountCreate {
	ac.mutation.SetSettings(ss)
	return ac
}

// SetPts sets the "pts" field.
func (ac *AccountCreate) SetPts(i int) *AccountCreate {
	ac.mutation.SetPts(i)
	return ac
}

// SetNillablePts sets the "pts" field if the given value is not nil.
func (ac *AccountCreate) SetNillablePts(i *int) *AccountCreate {
	if i != nil {
		ac.SetPts(*i)
	}
	return ac
}

// SetQts sets the "qts" field.
func (ac *AccountCreate) SetQts(i int) *AccountCreate {
	ac.mutation.SetQts(i)
	return ac
}

// SetNillableQts sets the "qts" field if the given value is not nil.
func (ac *AccountCreate) SetNillableQts(i *int) *AccountCreate {
	if i != nil {
		ac.SetQts(*i)
	}
	return ac
}

// SetSeq sets the "seq" field.
func (ac *AccountCreate) SetSeq(i int) *AccountCreate {
	ac.mutation.SetSeq(i)
	return ac
}

// SetNillableSeq sets the "seq" field if the given value is not nil.
func (ac *AccountCreate) SetNillableSeq(i *int) *AccountCreate {
	if i != nil {
		ac.SetSeq(*i)
	}
	return ac
}

// SetDate sets the "date" field.
func (ac *AccountCreate) SetDate(i int) *AccountCreate {
	ac.mutation.SetDate(i)
	return ac
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (ac *AccountCreate) SetNillableDate(i *int) *AccountCreate {
	if i != nil {
		ac.SetDate(*i)
	}
	return ac
}

// SetLastSyncAt sets the "last_sync_at" field.
func (ac *AccountCreate) SetLastSyncAt(i int64) *AccountCreate {
	ac.mutation.SetLastSyncAt(i)
	return ac
}

// SetNillableLastSyncAt sets the "last_sync_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableLastSyncAt(i *int64) *AccountCreate {
	if i != nil {
		ac.SetLastSyncAt(*i)
	}
	return ac
}

// SetCreatedAt sets the "created_at" field.
func (ac *AccountCreate) SetCreatedAt(i int64) *AccountCreate {
	ac.mutation.SetCreatedAt(i)
	return ac
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableCreatedAt(i *int64) *AccountCreate {
	if i != nil {
		ac.SetCreatedAt(*i)
	}
	return ac
}

// SetUpdatedAt sets the "updated_at" field.
func (ac *AccountCreate) SetUpdatedAt(i int64) *AccountCreate {
	ac.mutation.SetUpdatedAt(i)
	return ac
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (ac *AccountCreate) SetNillableUpdatedAt(i *int64) *AccountCreate {
	if i != nil {
		ac.SetUpdatedAt(*i)
	}
	return ac
}

// SetID sets the "id" field.
func (ac *AccountCreate) SetID(u uuid.UUID) *AccountCreate {
	ac.mutation.SetID(u)
	return ac
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ac *AccountCreate) SetNillableID(u *uuid.UUID) *AccountCreate {
	if u != nil {
		ac.SetID(*u)
	}
	return ac
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (ac *AccountCreate) AddMessageIDs(ids ...uuid.UUID) *AccountCreate {
	ac.mutation.AddMessageIDs(ids...)
	return ac
}

// AddMessages adds the "messages" edges to the Message entity.
func (ac *AccountCreate) AddMessages(m ...*Message) *AccountCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return ac.AddMessageIDs(ids...)
}

// AddChatIDs adds the "chats" edge to the Chat entity by IDs.
func (ac *AccountCreate) AddChatIDs(ids ...uuid.UUID) *AccountCreate {
	ac.mutation.AddChatIDs(ids...)
	return ac
}

// AddChats adds the "chats" edges to the Chat entity.
func (ac *AccountCreate) AddChats(c ...*Chat) *AccountCreate {
	ids := make([]uuid.UUID, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return ac.AddChatIDs(ids...)
}

// Mutation returns the AccountMutation object of the builder.
func (ac *AccountCreate) Mutation() *AccountMutation {
	return ac.mutation
}

// Save creates the Account in the database.
func (ac *AccountCreate) Save(ctx context.Context) (*Account, error) {
	ac.defaults()
	return withHooks(ctx, ac.sqlSave, ac.mutation, ac.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ac *AccountCreate) SaveX(ctx context.Context) *Account {
	v, err := ac.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ac *AccountCreate) Exec(ctx context.Context) error {
	_, err := ac.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ac *AccountCreate) ExecX(ctx context.Context) {
	if err := ac.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ac *AccountCreate) defaults() {
	if _, ok := ac.mutation.SessionData(); !ok {
		v := account.DefaultSessionData
		ac.mutation.SetSessionData(v)
	}
	if _, ok := ac.mutation.Pts(); !ok {
		v := account.DefaultPts
		ac.mutation.SetPts(v)
	}
	if _, ok := ac.mutation.Qts(); !ok {
		v := account.DefaultQts
		ac.mutation.SetQts(v)
	}
	if _, ok := ac.mutation.Seq(); !ok {
		v := account.DefaultSeq
		ac.mutation.SetSeq(v)
	}
	if _, ok := ac.mutation.Date(); !ok {
		v := account.DefaultDate
		ac.mutation.SetDate(v)
	}
	if _, ok := ac.mutation.LastSyncAt(); !ok {
		v := account.DefaultLastSyncAt
		ac.mutation.SetLastSyncAt(v)
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		v := account.DefaultCreatedAt()
		ac.mutation.SetCreatedAt(v)
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		v := account.DefaultUpdatedAt()
		ac.mutation.SetUpdatedAt(v)
	}
	if _, ok := ac.mutation.ID(); !ok {
		v := account.DefaultID()
		ac.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ac *AccountCreate) check() error {
	if _, ok := ac.mutation.Phone(); !ok {
		return &ValidationError{Name: "phone", err: errors.New(`ent: missing required field "Account.phone"`)}
	}
	if v, ok := ac.mutation.Phone(); ok {
		if err := account.PhoneValidator(v); err != nil {
			return &ValidationError{Name: "phone", err: fmt.Errorf(`ent: validator failed for field "Account.phone": %w`, err)}
		}
	}
	if _, ok := ac.mutation.SessionData(); !ok {
		return &ValidationError{Name: "session_data", err: errors.New(`ent: missing required field "Account.session_data"`)}
	}
	if _, ok := ac.mutation.Pts(); !ok {
		return &ValidationError{Name: "pts", err: errors.New(`ent: missing required field "Account.pts"`)}
	}
	if _, ok := ac.mutation.Qts(); !ok {
		return &ValidationError{Name: "qts", err: errors.New(`ent: missing required field "Account.qts"`)}
	}
	if _, ok := ac.mutation.Seq(); !ok {
		return &ValidationError{Name: "seq", err: errors.New(`ent: missing required field "Account.seq"`)}
	}
	if _, ok := ac.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "Account.date"`)}
	}
	if _, ok := ac.mutation.LastSyncAt(); !ok {
		return &ValidationError{Name: "last_sync_at", err: errors.New(`ent: missing required field "Account.last_sync_at"`)}
	}
	if _, ok := ac.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Account.created_at"`)}
	}
	if _, ok := ac.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Account.updated_at"`)}
	}
	return nil
}

func (ac *AccountCreate) sqlSave(ctx context.Context) (*Account, error) {
	if err := ac.check(); err != nil {
		return nil, err
	}
	_node, _spec := ac.createSpec()
	if err := sqlgraph.CreateNode(ctx, ac.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ac.mutation.id = &_node.ID
	ac.mutation.done = true
	return _node, nil
}

func (ac *AccountCreate) createSpec() (*Account, *sqlgraph.CreateSpec) {
	var (
		_node = &Account{config: ac.config}
		_spec = sqlgraph.NewCreateSpec(account.Table, sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID))
	)
	if id, ok := ac.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ac.mutation.Phone(); ok {
		_spec.SetField(account.FieldPhone, field.TypeString, value)
		_node.Phone = value
	}
	if value, ok := ac.mutation.SessionData(); ok {
		_spec.SetField(account.FieldSessionData, field.TypeString, value)
		_node.SessionData = value
	}
	if value, ok := ac.mutation.Settings(); ok {
		_spec.SetField(account.FieldSettings, field.TypeJSON, value)
		_node.Settings = value
	}
	if value, ok := ac.mutation.Pts(); ok {
		_spec.SetField(account.FieldPts, field.TypeInt, value)
		_node.Pts = value
	}
	if value, ok := ac.mutation.Qts(); ok {
		_spec.SetField(account.FieldQts, field.TypeInt, value)
		_node.Qts = value
	}
	if value, ok := ac.mutation.Seq(); ok {
		_spec.SetField(account.FieldSeq, field.TypeInt, value)
		_node.Seq = value
	}
	if value, ok := ac.mutation.Date(); ok {
		_spec.SetField(account.FieldDate, field.TypeInt, value)
		_node.Date = value
	}
	if value, ok := ac.mutation.LastSyncAt(); ok {
		_spec.SetField(account.FieldLastSyncAt, field.TypeInt64, value)
		_node.LastSyncAt = value
	}
	if value, ok := ac.mutation.CreatedAt(); ok {
		_spec.SetField(account.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := ac.mutation.UpdatedAt(); ok {
		_spec.SetField(account.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := ac.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.MessagesTable,
			Columns: []string{account.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := ac.mutation.ChatsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   account.ChatsTable,
			Columns: []string{account.ChatsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// AccountCreateBulk is the builder for creating many Account entities in bulk.
type AccountCreateBulk struct {
	config
	err      error
	builders []*AccountCreate
}

// Save creates the Account entities in the database.
func (acb *AccountCreateBulk) Save(ctx context.Context) ([]*Account, error) {
	if acb.err != nil {
		return nil, acb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(acb.builders))
	nodes := make([]*Account, len(acb.builders))
	mutators := make([]Mutator, len(acb.builders))
	for i := range acb.builders {
		func(i int, root context.Context) {
			builder := acb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, acb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, acb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, acb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (acb *AccountCreateBulk) SaveX(ctx context.Context) []*Account {
	v, err := acb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (acb *AccountCreateBulk) Exec(ctx context.Context) error {
	_, err := acb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (acb *AccountCreateBulk) ExecX(ctx context.Context) {
	if err := acb.Exec(ctx); err != nil {
		panic(err)
	}
}
