// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
)

// ChatCreate is the builder for creating a Chat entity.
type ChatCreate struct {
	config
	mutation *ChatMutation
	hooks    []Hook
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (cc *ChatCreate) SetOwnerAccountID(u uuid.UUID) *ChatCreate {
	cc.mutation.SetOwnerAccountID(u)
	return cc
}

// SetPlatform sets the "platform" field.
func (cc *ChatCreate) SetPlatform(s string) *ChatCreate {
	cc.mutation.SetPlatform(s)
	return cc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (cc *ChatCreate) SetNillablePlatform(s *string) *ChatCreate {
	if s != nil {
		cc.SetPlatform(*s)
	}
	return cc
}

// SetChatID sets the "chat_id" field.
func (cc *ChatCreate) SetChatID(s string) *ChatCreate {
	cc.mutation.SetChatID(s)
	return cc
}

// SetChatName sets the "chat_name" field.
func (cc *ChatCreate) SetChatName(s string) *ChatCreate {
	cc.mutation.SetChatName(s)
	return cc
}

// SetNillableChatName sets the "chat_name" field if the given value is not nil.
func (cc *ChatCreate) SetNillableChatName(s *string) *ChatCreate {
	if s != nil {
		cc.SetChatName(*s)
	}
	return cc
}

// SetChatType sets the "chat_type" field.
func (cc *ChatCreate) SetChatType(s string) *ChatCreate {
	cc.mutation.SetChatType(s)
	return cc
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (cc *ChatCreate) SetNillableChatType(s *string) *ChatCreate {
	if s != nil {
		cc.SetChatType(*s)
	}
	return cc
}

// SetChatUsername sets the "chat_username" field.
func (cc *ChatCreate) SetChatUsername(s string) *ChatCreate {
	cc.mutation.SetChatUsername(s)
	return cc
}

// SetNillableChatUsername sets the "chat_username" field if the given value is not nil.
func (cc *ChatCreate) SetNillableChatUsername(s *string) *ChatCreate {
	if s != nil {
		cc.SetChatUsername(*s)
	}
	return cc
}

// SetNote sets the "note" field.
func (cc *ChatCreate) SetNote(s string) *ChatCreate {
	cc.mutation.SetNote(s)
	return cc
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (cc *ChatCreate) SetNillableNote(s *string) *ChatCreate {
	if s != nil {
		cc.SetNote(*s)
	}
	return cc
}

// SetCreatedAt sets the "created_at" field.
func (cc *ChatCreate) SetCreatedAt(i int64) *ChatCreate {
	cc.mutation.SetCreatedAt(i)
	return cc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cc *ChatCreate) SetNillableCreatedAt(i *int64) *ChatCreate {
	if i != nil {
		cc.SetCreatedAt(*i)
	}
	return cc
}

// SetUpdatedAt sets the "updated_at" field.
func (cc *ChatCreate) SetUpdatedAt(i int64) *ChatCreate {
	cc.mutation.SetUpdatedAt(i)
	return cc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (cc *ChatCreate) SetNillableUpdatedAt(i *int64) *ChatCreate {
	if i != nil {
		cc.SetUpdatedAt(*i)
	}
	return cc
}

// SetID sets the "id" field.
func (cc *ChatCreate) SetID(u uuid.UUID) *ChatCreate {
	cc.mutation.SetID(u)
	return cc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (cc *ChatCreate) SetNillableID(u *uuid.UUID) *ChatCreate {
	if u != nil {
		cc.SetID(*u)
	}
	return cc
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (cc *ChatCreate) SetOwnerID(id uuid.UUID) *ChatCreate {
	cc.mutation.SetOwnerID(id)
	return cc
}

// SetOwner sets the "owner" edge to the Account entity.
func (cc *ChatCreate) SetOwner(a *Account) *ChatCreate {
	return cc.SetOwnerID(a.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (cc *ChatCreate) AddMessageIDs(ids ...uuid.UUID) *ChatCreate {
	cc.mutation.AddMessageIDs(ids...)
	return cc
}

// AddMessages adds the "messages" edges to the Message entity.
func (cc *ChatCreate) AddMessages(m ...*Message) *ChatCreate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cc.AddMessageIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (cc *ChatCreate) Mutation() *ChatMutation {
	return cc.mutation
}

// Save creates the Chat in the database.
func (cc *ChatCreate) Save(ctx context.Context) (*Chat, error) {
	cc.defaults()
	return withHooks(ctx, cc.sqlSave, cc.mutation, cc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (cc *ChatCreate) SaveX(ctx context.Context) *Chat {
	v, err := cc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (cc *ChatCreate) Exec(ctx context.Context) error {
	_, err := cc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cc *ChatCreate) ExecX(ctx context.Context) {
	if err := cc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cc *ChatCreate) defaults() {
	if _, ok := cc.mutation.Platform(); !ok {
		v := chat.DefaultPlatform
		cc.mutation.SetPlatform(v)
	}
	if _, ok := cc.mutation.ChatName(); !ok {
		v := chat.DefaultChatName
		cc.mutation.SetChatName(v)
	}
	if _, ok := cc.mutation.ChatType(); !ok {
		v := chat.DefaultChatType
		cc.mutation.SetChatType(v)
	}
	if _, ok := cc.mutation.Note(); !ok {
		v := chat.DefaultNote
		cc.mutation.SetNote(v)
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		v := chat.DefaultCreatedAt()
		cc.mutation.SetCreatedAt(v)
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		v := chat.DefaultUpdatedAt()
		cc.mutation.SetUpdatedAt(v)
	}
	if _, ok := cc.mutation.ID(); !ok {
		v := chat.DefaultID()
		cc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cc *ChatCreate) check() error {
	if _, ok := cc.mutation.OwnerAccountID(); !ok {
		return &ValidationError{Name: "owner_account_id", err: errors.New(`ent: missing required field "Chat.owner_account_id"`)}
	}
	if _, ok := cc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Chat.platform"`)}
	}
	if _, ok := cc.mutation.ChatID(); !ok {
		return &ValidationError{Name: "chat_id", err: errors.New(`ent: missing required field "Chat.chat_id"`)}
	}
	if v, ok := cc.mutation.ChatID(); ok {
		if err := chat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "Chat.chat_id": %w`, err)}
		}
	}
	if _, ok := cc.mutation.ChatName(); !ok {
		return &ValidationError{Name: "chat_name", err: errors.New(`ent: missing required field "Chat.chat_name"`)}
	}
	if _, ok := cc.mutation.ChatType(); !ok {
		return &ValidationError{Name: "chat_type", err: errors.New(`ent: missing required field "Chat.chat_type"`)}
	}
	if _, ok := cc.mutation.Note(); !ok {
		return &ValidationError{Name: "note", err: errors.New(`ent: missing required field "Chat.note"`)}
	}
	if _, ok := cc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Chat.created_at"`)}
	}
	if _, ok := cc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Chat.updated_at"`)}
	}
	if len(cc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Chat.owner"`)}
	}
	return nil
}

func (cc *ChatCreate) sqlSave(ctx context.Context) (*Chat, error) {
	if err := cc.check(); err != nil {
		return nil, err
	}
	_node, _spec := cc.createSpec()
	if err := sqlgraph.CreateNode(ctx, cc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	cc.mutation.id = &_node.ID
	cc.mutation.done = true
	return _node, nil
}

func (cc *ChatCreate) createSpec() (*Chat, *sqlgraph.CreateSpec) {
	var (
		_node = &Chat{config: cc.config}
		_spec = sqlgraph.NewCreateSpec(chat.Table, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	)
	if id, ok := cc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := cc.mutation.Platform(); ok {
		_spec.SetField(chat.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := cc.mutation.ChatID(); ok {
		_spec.SetField(chat.FieldChatID, field.TypeString, value)
		_node.ChatID = value
	}
	if value, ok := cc.mutation.ChatName(); ok {
		_spec.SetField(chat.FieldChatName, field.TypeString, value)
		_node.ChatName = value
	}
	if value, ok := cc.mutation.ChatType(); ok {
		_spec.SetField(chat.FieldChatType, field.TypeString, value)
		_node.ChatType = value
	}
	if value, ok := cc.mutation.ChatUsername(); ok {
		_spec.SetField(chat.FieldChatUsername, field.TypeString, value)
		_node.ChatUsername = &value
	}
	if value, ok := cc.mutation.Note(); ok {
		_spec.SetField(chat.FieldNote, field.TypeString, value)
		_node.Note = value
	}
	if value, ok := cc.mutation.CreatedAt(); ok {
		_spec.SetField(chat.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := cc.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if nodes := cc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.OwnerTable,
			Columns: []string{chat.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := cc.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ChatCreateBulk is the builder for creating many Chat entities in bulk.
type ChatCreateBulk struct {
	config
	err      error
	builders []*ChatCreate
}

// Save creates the Chat entities in the database.
func (ccb *ChatCreateBulk) Save(ctx context.Context) ([]*Chat, error) {
	if ccb.err != nil {
		return nil, ccb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(ccb.builders))
	nodes := make([]*Chat, len(ccb.builders))
	mutators := make([]Mutator, len(ccb.builders))
	for i := range ccb.builders {
		func(i int, root context.Context) {
			builder := ccb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ChatMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ccb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ccb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ccb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ccb *ChatCreateBulk) SaveX(ctx context.Context) []*Chat {
	v, err := ccb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ccb *ChatCreateBulk) Exec(ctx context.Context) error {
	_, err := ccb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ccb *ChatCreateBulk) ExecX(ctx context.Context) {
	if err := ccb.Exec(ctx); err != nil {
		panic(err)
	}
}
