// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
	"github.com/groupultra/telegram-search/ent/predicate"
)

// ChatUpdate is the builder for updating Chat entities.
type ChatUpdate struct {
	config
	hooks    []Hook
	mutation *ChatMutation
}

// Where appends a list predicates to the ChatUpdate builder.
func (cu *ChatUpdate) Where(ps ...predicate.Chat) *ChatUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (cu *ChatUpdate) SetOwnerAccountID(u uuid.UUID) *ChatUpdate {
	cu.mutation.SetOwnerAccountID(u)
	return cu
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableOwnerAccountID(u *uuid.UUID) *ChatUpdate {
	if u != nil {
		cu.SetOwnerAccountID(*u)
	}
	return cu
}

// SetPlatform sets the "platform" field.
func (cu *ChatUpdate) SetPlatform(s string) *ChatUpdate {
	cu.mutation.SetPlatform(s)
	return cu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (cu *ChatUpdate) SetNillablePlatform(s *string) *ChatUpdate {
	if s != nil {
		cu.SetPlatform(*s)
	}
	return cu
}

// SetChatID sets the "chat_id" field.
func (cu *ChatUpdate) SetChatID(s string) *ChatUpdate {
	cu.mutation.SetChatID(s)
	return cu
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableChatID(s *string) *ChatUpdate {
	if s != nil {
		cu.SetChatID(*s)
	}
	return cu
}

// SetChatName sets the "chat_name" field.
func (cu *ChatUpdate) SetChatName(s string) *ChatUpdate {
	cu.mutation.SetChatName(s)
	return cu
}

// SetNillableChatName sets the "chat_name" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableChatName(s *string) *ChatUpdate {
	if s != nil {
		cu.SetChatName(*s)
	}
	return cu
}

// SetChatType sets the "chat_type" field.
func (cu *ChatUpdate) SetChatType(s string) *ChatUpdate {
	cu.mutation.SetChatType(s)
	return cu
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableChatType(s *string) *ChatUpdate {
	if s != nil {
		cu.SetChatType(*s)
	}
	return cu
}

// SetChatUsername sets the "chat_username" field.
func (cu *ChatUpdate) SetChatUsername(s string) *ChatUpdate {
	cu.mutation.SetChatUsername(s)
	return cu
}

// SetNillableChatUsername sets the "chat_username" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableChatUsername(s *string) *ChatUpdate {
	if s != nil {
		cu.SetChatUsername(*s)
	}
	return cu
}

// ClearChatUsername clears the value of the "chat_username" field.
func (cu *ChatUpdate) ClearChatUsername() *ChatUpdate {
	cu.mutation.ClearChatUsername()
	return cu
}

// SetNote sets the "note" field.
func (cu *ChatUpdate) SetNote(s string) *ChatUpdate {
	cu.mutation.SetNote(s)
	return cu
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (cu *ChatUpdate) SetNillableNote(s *string) *ChatUpdate {
	if s != nil {
		cu.SetNote(*s)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *ChatUpdate) SetUpdatedAt(i int64) *ChatUpdate {
	cu.mutation.ResetUpdatedAt()
	cu.mutation.SetUpdatedAt(i)
	return cu
}

// AddUpdatedAt adds i to the "updated_at" field.
func (cu *ChatUpdate) AddUpdatedAt(i int64) *ChatUpdate {
	cu.mutation.AddUpdatedAt(i)
	return cu
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (cu *ChatUpdate) SetOwnerID(id uuid.UUID) *ChatUpdate {
	cu.mutation.SetOwnerID(id)
	return cu
}

// SetOwner sets the "owner" edge to the Account entity.
func (cu *ChatUpdate) SetOwner(a *Account) *ChatUpdate {
	return cu.SetOwnerID(a.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (cu *ChatUpdate) AddMessageIDs(ids ...uuid.UUID) *ChatUpdate {
	cu.mutation.AddMessageIDs(ids...)
	return cu
}

// AddMessages adds the "messages" edges to the Message entity.
func (cu *ChatUpdate) AddMessages(m ...*Message) *ChatUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cu.AddMessageIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (cu *ChatUpdate) Mutation() *ChatMutation {
	return cu.mutation
}

// ClearOwner clears the "owner" edge to the Account entity.
func (cu *ChatUpdate) ClearOwner() *ChatUpdate {
	cu.mutation.ClearOwner()
	return cu
}

// ClearMessages clears all "messages" edges to the Message entity.
func (cu *ChatUpdate) ClearMessages() *ChatUpdate {
	cu.mutation.ClearMessages()
	return cu
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (cu *ChatUpdate) RemoveMessageIDs(ids ...uuid.UUID) *ChatUpdate {
	cu.mutation.RemoveMessageIDs(ids...)
	return cu
}

// RemoveMessages removes "messages" edges to Message entities.
func (cu *ChatUpdate) RemoveMessages(m ...*Message) *ChatUpdate {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cu.RemoveMessageIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *ChatUpdate) Save(ctx context.Context) (int, error) {
	cu.defaults()
	return withHooks(ctx, cu.sqlSave, cu.mutation, cu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cu *ChatUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *ChatUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *ChatUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *ChatUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *ChatUpdate) check() error {
	if v, ok := cu.mutation.ChatID(); ok {
		if err := chat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "Chat.chat_id": %w`, err)}
		}
	}
	if cu.mutation.OwnerCleared() && len(cu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chat.owner"`)
	}
	return nil
}

func (cu *ChatUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := cu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.Platform(); ok {
		_spec.SetField(chat.FieldPlatform, field.TypeString, value)
	}
	if value, ok := cu.mutation.ChatID(); ok {
		_spec.SetField(chat.FieldChatID, field.TypeString, value)
	}
	if value, ok := cu.mutation.ChatName(); ok {
		_spec.SetField(chat.FieldChatName, field.TypeString, value)
	}
	if value, ok := cu.mutation.ChatType(); ok {
		_spec.SetField(chat.FieldChatType, field.TypeString, value)
	}
	if value, ok := cu.mutation.ChatUsername(); ok {
		_spec.SetField(chat.FieldChatUsername, field.TypeString, value)
	}
	if cu.mutation.ChatUsernameCleared() {
		_spec.ClearField(chat.FieldChatUsername, field.TypeString)
	}
	if value, ok := cu.mutation.Note(); ok {
		_spec.SetField(chat.FieldNote, field.TypeString, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cu.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(chat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if cu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.OwnerTable,
			Columns: []string{chat.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.OwnerTable,
			Columns: []string{chat.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !cu.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	cu.mutation.done = true
	return n, nil
}

// ChatUpdateOne is the builder for updating a single Chat entity.
type ChatUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ChatMutation
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (cuo *ChatUpdateOne) SetOwnerAccountID(u uuid.UUID) *ChatUpdateOne {
	cuo.mutation.SetOwnerAccountID(u)
	return cuo
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableOwnerAccountID(u *uuid.UUID) *ChatUpdateOne {
	if u != nil {
		cuo.SetOwnerAccountID(*u)
	}
	return cuo
}

// SetPlatform sets the "platform" field.
func (cuo *ChatUpdateOne) SetPlatform(s string) *ChatUpdateOne {
	cuo.mutation.SetPlatform(s)
	return cuo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillablePlatform(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetPlatform(*s)
	}
	return cuo
}

// SetChatID sets the "chat_id" field.
func (cuo *ChatUpdateOne) SetChatID(s string) *ChatUpdateOne {
	cuo.mutation.SetChatID(s)
	return cuo
}

// SetNillableChatID sets the "chat_id" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableChatID(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetChatID(*s)
	}
	return cuo
}

// SetChatName sets the "chat_name" field.
func (cuo *ChatUpdateOne) SetChatName(s string) *ChatUpdateOne {
	cuo.mutation.SetChatName(s)
	return cuo
}

// SetNillableChatName sets the "chat_name" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableChatName(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetChatName(*s)
	}
	return cuo
}

// SetChatType sets the "chat_type" field.
func (cuo *ChatUpdateOne) SetChatType(s string) *ChatUpdateOne {
	cuo.mutation.SetChatType(s)
	return cuo
}

// SetNillableChatType sets the "chat_type" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableChatType(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetChatType(*s)
	}
	return cuo
}

// SetChatUsername sets the "chat_username" field.
func (cuo *ChatUpdateOne) SetChatUsername(s string) *ChatUpdateOne {
	cuo.mutation.SetChatUsername(s)
	return cuo
}

// SetNillableChatUsername sets the "chat_username" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableChatUsername(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetChatUsername(*s)
	}
	return cuo
}

// ClearChatUsername clears the value of the "chat_username" field.
func (cuo *ChatUpdateOne) ClearChatUsername() *ChatUpdateOne {
	cuo.mutation.ClearChatUsername()
	return cuo
}

// SetNote sets the "note" field.
func (cuo *ChatUpdateOne) SetNote(s string) *ChatUpdateOne {
	cuo.mutation.SetNote(s)
	return cuo
}

// SetNillableNote sets the "note" field if the given value is not nil.
func (cuo *ChatUpdateOne) SetNillableNote(s *string) *ChatUpdateOne {
	if s != nil {
		cuo.SetNote(*s)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *ChatUpdateOne) SetUpdatedAt(i int64) *ChatUpdateOne {
	cuo.mutation.ResetUpdatedAt()
	cuo.mutation.SetUpdatedAt(i)
	return cuo
}

// AddUpdatedAt adds i to the "updated_at" field.
func (cuo *ChatUpdateOne) AddUpdatedAt(i int64) *ChatUpdateOne {
	cuo.mutation.AddUpdatedAt(i)
	return cuo
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (cuo *ChatUpdateOne) SetOwnerID(id uuid.UUID) *ChatUpdateOne {
	cuo.mutation.SetOwnerID(id)
	return cuo
}

// SetOwner sets the "owner" edge to the Account entity.
func (cuo *ChatUpdateOne) SetOwner(a *Account) *ChatUpdateOne {
	return cuo.SetOwnerID(a.ID)
}

// AddMessageIDs adds the "messages" edge to the Message entity by IDs.
func (cuo *ChatUpdateOne) AddMessageIDs(ids ...uuid.UUID) *ChatUpdateOne {
	cuo.mutation.AddMessageIDs(ids...)
	return cuo
}

// AddMessages adds the "messages" edges to the Message entity.
func (cuo *ChatUpdateOne) AddMessages(m ...*Message) *ChatUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cuo.AddMessageIDs(ids...)
}

// Mutation returns the ChatMutation object of the builder.
func (cuo *ChatUpdateOne) Mutation() *ChatMutation {
	return cuo.mutation
}

// ClearOwner clears the "owner" edge to the Account entity.
func (cuo *ChatUpdateOne) ClearOwner() *ChatUpdateOne {
	cuo.mutation.ClearOwner()
	return cuo
}

// ClearMessages clears all "messages" edges to the Message entity.
func (cuo *ChatUpdateOne) ClearMessages() *ChatUpdateOne {
	cuo.mutation.ClearMessages()
	return cuo
}

// RemoveMessageIDs removes the "messages" edge to Message entities by IDs.
func (cuo *ChatUpdateOne) RemoveMessageIDs(ids ...uuid.UUID) *ChatUpdateOne {
	cuo.mutation.RemoveMessageIDs(ids...)
	return cuo
}

// RemoveMessages removes "messages" edges to Message entities.
func (cuo *ChatUpdateOne) RemoveMessages(m ...*Message) *ChatUpdateOne {
	ids := make([]uuid.UUID, len(m))
	for i := range m {
		ids[i] = m[i].ID
	}
	return cuo.RemoveMessageIDs(ids...)
}

// Where appends a list predicates to the ChatUpdate builder.
func (cuo *ChatUpdateOne) Where(ps ...predicate.Chat) *ChatUpdateOne {
	cuo.mutation.Where(ps...)
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *ChatUpdateOne) Select(field string, fields ...string) *ChatUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Chat entity.
func (cuo *ChatUpdateOne) Save(ctx context.Context) (*Chat, error) {
	cuo.defaults()
	return withHooks(ctx, cuo.sqlSave, cuo.mutation, cuo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *ChatUpdateOne) SaveX(ctx context.Context) *Chat {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *ChatUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *ChatUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *ChatUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := chat.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *ChatUpdateOne) check() error {
	if v, ok := cuo.mutation.ChatID(); ok {
		if err := chat.ChatIDValidator(v); err != nil {
			return &ValidationError{Name: "chat_id", err: fmt.Errorf(`ent: validator failed for field "Chat.chat_id": %w`, err)}
		}
	}
	if cuo.mutation.OwnerCleared() && len(cuo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Chat.owner"`)
	}
	return nil
}

func (cuo *ChatUpdateOne) sqlSave(ctx context.Context) (_node *Chat, err error) {
	if err := cuo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(chat.Table, chat.Columns, sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID))
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Chat.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chat.FieldID)
		for _, f := range fields {
			if !chat.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != chat.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.Platform(); ok {
		_spec.SetField(chat.FieldPlatform, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ChatID(); ok {
		_spec.SetField(chat.FieldChatID, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ChatName(); ok {
		_spec.SetField(chat.FieldChatName, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ChatType(); ok {
		_spec.SetField(chat.FieldChatType, field.TypeString, value)
	}
	if value, ok := cuo.mutation.ChatUsername(); ok {
		_spec.SetField(chat.FieldChatUsername, field.TypeString, value)
	}
	if cuo.mutation.ChatUsernameCleared() {
		_spec.ClearField(chat.FieldChatUsername, field.TypeString)
	}
	if value, ok := cuo.mutation.Note(); ok {
		_spec.SetField(chat.FieldNote, field.TypeString, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(chat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := cuo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(chat.FieldUpdatedAt, field.TypeInt64, value)
	}
	if cuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.OwnerTable,
			Columns: []string{chat.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   chat.OwnerTable,
			Columns: []string{chat.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedMessagesIDs(); len(nodes) > 0 && !cuo.mutation.MessagesCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.MessagesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   chat.MessagesTable,
			Columns: []string{chat.MessagesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Chat{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{chat.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	cuo.mutation.done = true
	return _node, nil
}
