// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
)

// MessageCreate is the builder for creating a Message entity.
type MessageCreate struct {
	config
	mutation *MessageMutation
	hooks    []Hook
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (mc *MessageCreate) SetOwnerAccountID(u uuid.UUID) *MessageCreate {
	mc.mutation.SetOwnerAccountID(u)
	return mc
}

// SetInChatID sets the "in_chat_id" field.
func (mc *MessageCreate) SetInChatID(u uuid.UUID) *MessageCreate {
	mc.mutation.SetInChatID(u)
	return mc
}

// SetPlatform sets the "platform" field.
func (mc *MessageCreate) SetPlatform(s string) *MessageCreate {
	mc.mutation.SetPlatform(s)
	return mc
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mc *MessageCreate) SetNillablePlatform(s *string) *MessageCreate {
	if s != nil {
		mc.SetPlatform(*s)
	}
	return mc
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (mc *MessageCreate) SetPlatformMessageID(s string) *MessageCreate {
	mc.mutation.SetPlatformMessageID(s)
	return mc
}

// SetFromID sets the "from_id" field.
func (mc *MessageCreate) SetFromID(s string) *MessageCreate {
	mc.mutation.SetFromID(s)
	return mc
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableFromID(s *string) *MessageCreate {
	if s != nil {
		mc.SetFromID(*s)
	}
	return mc
}

// SetFromName sets the "from_name" field.
func (mc *MessageCreate) SetFromName(s string) *MessageCreate {
	mc.mutation.SetFromName(s)
	return mc
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (mc *MessageCreate) SetNillableFromName(s *string) *MessageCreate {
	if s != nil {
		mc.SetFromName(*s)
	}
	return mc
}

// SetContent sets the "content" field.
func (mc *MessageCreate) SetContent(s string) *MessageCreate {
	mc.mutation.SetContent(s)
	return mc
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (mc *MessageCreate) SetNillableContent(s *string) *MessageCreate {
	if s != nil {
		mc.SetContent(*s)
	}
	return mc
}

// SetIsReply sets the "is_reply" field.
func (mc *MessageCreate) SetIsReply(b bool) *MessageCreate {
	mc.mutation.SetIsReply(b)
	return mc
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (mc *MessageCreate) SetNillableIsReply(b *bool) *MessageCreate {
	if b != nil {
		mc.SetIsReply(*b)
	}
	return mc
}

// SetReplyToID sets the "reply_to_id" field.
func (mc *MessageCreate) SetReplyToID(s string) *MessageCreate {
	mc.mutation.SetReplyToID(s)
	return mc
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableReplyToID(s *string) *MessageCreate {
	if s != nil {
		mc.SetReplyToID(*s)
	}
	return mc
}

// SetReplyToName sets the "reply_to_name" field.
func (mc *MessageCreate) SetReplyToName(s string) *MessageCreate {
	mc.mutation.SetReplyToName(s)
	return mc
}

// SetNillableReplyToName sets the "reply_to_name" field if the given value is not nil.
func (mc *MessageCreate) SetNillableReplyToName(s *string) *MessageCreate {
	if s != nil {
		mc.SetReplyToName(*s)
	}
	return mc
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (mc *MessageCreate) SetPlatformTimestamp(i int64) *MessageCreate {
	mc.mutation.SetPlatformTimestamp(i)
	return mc
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (mc *MessageCreate) SetNillablePlatformTimestamp(i *int64) *MessageCreate {
	if i != nil {
		mc.SetPlatformTimestamp(*i)
	}
	return mc
}

// SetContentVectorModel sets the "content_vector_model" field.
func (mc *MessageCreate) SetContentVectorModel(s string) *MessageCreate {
	mc.mutation.SetContentVectorModel(s)
	return mc
}

// SetNillableContentVectorModel sets the "content_vector_model" field if the given value is not nil.
func (mc *MessageCreate) SetNillableContentVectorModel(s *string) *MessageCreate {
	if s != nil {
		mc.SetContentVectorModel(*s)
	}
	return mc
}

// SetJiebaTokens sets the "jieba_tokens" field.
func (mc *MessageCreate) SetJiebaTokens(s []string) *MessageCreate {
	mc.mutation.SetJiebaTokens(s)
	return mc
}

// SetCreatedAt sets the "created_at" field.
func (mc *MessageCreate) SetCreatedAt(i int64) *MessageCreate {
	mc.mutation.SetCreatedAt(i)
	return mc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableCreatedAt(i *int64) *MessageCreate {
	if i != nil {
		mc.SetCreatedAt(*i)
	}
	return mc
}

// SetUpdatedAt sets the "updated_at" field.
func (mc *MessageCreate) SetUpdatedAt(i int64) *MessageCreate {
	mc.mutation.SetUpdatedAt(i)
	return mc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableUpdatedAt(i *int64) *MessageCreate {
	if i != nil {
		mc.SetUpdatedAt(*i)
	}
	return mc
}

// SetDeletedAt sets the "deleted_at" field.
func (mc *MessageCreate) SetDeletedAt(i int64) *MessageCreate {
	mc.mutation.SetDeletedAt(i)
	return mc
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mc *MessageCreate) SetNillableDeletedAt(i *int64) *MessageCreate {
	if i != nil {
		mc.SetDeletedAt(*i)
	}
	return mc
}

// SetID sets the "id" field.
func (mc *MessageCreate) SetID(u uuid.UUID) *MessageCreate {
	mc.mutation.SetID(u)
	return mc
}

// SetNillableID sets the "id" field if the given value is not nil.
func (mc *MessageCreate) SetNillableID(u *uuid.UUID) *MessageCreate {
	if u != nil {
		mc.SetID(*u)
	}
	return mc
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (mc *MessageCreate) SetOwnerID(id uuid.UUID) *MessageCreate {
	mc.mutation.SetOwnerID(id)
	return mc
}

// SetOwner sets the "owner" edge to the Account entity.
func (mc *MessageCreate) SetOwner(a *Account) *MessageCreate {
	return mc.SetOwnerID(a.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (mc *MessageCreate) SetChatID(id uuid.UUID) *MessageCreate {
	mc.mutation.SetChatID(id)
	return mc
}

// SetChat sets the "chat" edge to the Chat entity.
func (mc *MessageCreate) SetChat(c *Chat) *MessageCreate {
	return mc.SetChatID(c.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mc *MessageCreate) Mutation() *MessageMutation {
	return mc.mutation
}

// Save creates the Message in the database.
func (mc *MessageCreate) Save(ctx context.Context) (*Message, error) {
	mc.defaults()
	return withHooks(ctx, mc.sqlSave, mc.mutation, mc.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (mc *MessageCreate) SaveX(ctx context.Context) *Message {
	v, err := mc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mc *MessageCreate) Exec(ctx context.Context) error {
	_, err := mc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mc *MessageCreate) ExecX(ctx context.Context) {
	if err := mc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mc *MessageCreate) defaults() {
	if _, ok := mc.mutation.Platform(); !ok {
		v := message.DefaultPlatform
		mc.mutation.SetPlatform(v)
	}
	if _, ok := mc.mutation.FromID(); !ok {
		v := message.DefaultFromID
		mc.mutation.SetFromID(v)
	}
	if _, ok := mc.mutation.FromName(); !ok {
		v := message.DefaultFromName
		mc.mutation.SetFromName(v)
	}
	if _, ok := mc.mutation.Content(); !ok {
		v := message.DefaultContent
		mc.mutation.SetContent(v)
	}
	if _, ok := mc.mutation.IsReply(); !ok {
		v := message.DefaultIsReply
		mc.mutation.SetIsReply(v)
	}
	if _, ok := mc.mutation.ReplyToID(); !ok {
		v := message.DefaultReplyToID
		mc.mutation.SetReplyToID(v)
	}
	if _, ok := mc.mutation.ReplyToName(); !ok {
		v := message.DefaultReplyToName
		mc.mutation.SetReplyToName(v)
	}
	if _, ok := mc.mutation.PlatformTimestamp(); !ok {
		v := message.DefaultPlatformTimestamp
		mc.mutation.SetPlatformTimestamp(v)
	}
	if _, ok := mc.mutation.ContentVectorModel(); !ok {
		v := message.DefaultContentVectorModel
		mc.mutation.SetContentVectorModel(v)
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		v := message.DefaultCreatedAt()
		mc.mutation.SetCreatedAt(v)
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		v := message.DefaultUpdatedAt()
		mc.mutation.SetUpdatedAt(v)
	}
	if _, ok := mc.mutation.DeletedAt(); !ok {
		v := message.DefaultDeletedAt
		mc.mutation.SetDeletedAt(v)
	}
	if _, ok := mc.mutation.ID(); !ok {
		v := message.DefaultID()
		mc.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mc *MessageCreate) check() error {
	if _, ok := mc.mutation.OwnerAccountID(); !ok {
		return &ValidationError{Name: "owner_account_id", err: errors.New(`ent: missing required field "Message.owner_account_id"`)}
	}
	if _, ok := mc.mutation.InChatID(); !ok {
		return &ValidationError{Name: "in_chat_id", err: errors.New(`ent: missing required field "Message.in_chat_id"`)}
	}
	if _, ok := mc.mutation.Platform(); !ok {
		return &ValidationError{Name: "platform", err: errors.New(`ent: missing required field "Message.platform"`)}
	}
	if _, ok := mc.mutation.PlatformMessageID(); !ok {
		return &ValidationError{Name: "platform_message_id", err: errors.New(`ent: missing required field "Message.platform_message_id"`)}
	}
	if v, ok := mc.mutation.PlatformMessageID(); ok {
		if err := message.PlatformMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_message_id", err: fmt.Errorf(`ent: validator failed for field "Message.platform_message_id": %w`, err)}
		}
	}
	if _, ok := mc.mutation.FromID(); !ok {
		return &ValidationError{Name: "from_id", err: errors.New(`ent: missing required field "Message.from_id"`)}
	}
	if _, ok := mc.mutation.FromName(); !ok {
		return &ValidationError{Name: "from_name", err: errors.New(`ent: missing required field "Message.from_name"`)}
	}
	if _, ok := mc.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "Message.content"`)}
	}
	if _, ok := mc.mutation.IsReply(); !ok {
		return &ValidationError{Name: "is_reply", err: errors.New(`ent: missing required field "Message.is_reply"`)}
	}
	if _, ok := mc.mutation.ReplyToID(); !ok {
		return &ValidationError{Name: "reply_to_id", err: errors.New(`ent: missing required field "Message.reply_to_id"`)}
	}
	if _, ok := mc.mutation.ReplyToName(); !ok {
		return &ValidationError{Name: "reply_to_name", err: errors.New(`ent: missing required field "Message.reply_to_name"`)}
	}
	if _, ok := mc.mutation.PlatformTimestamp(); !ok {
		return &ValidationError{Name: "platform_timestamp", err: errors.New(`ent: missing required field "Message.platform_timestamp"`)}
	}
	if _, ok := mc.mutation.ContentVectorModel(); !ok {
		return &ValidationError{Name: "content_vector_model", err: errors.New(`ent: missing required field "Message.content_vector_model"`)}
	}
	if _, ok := mc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Message.created_at"`)}
	}
	if _, ok := mc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Message.updated_at"`)}
	}
	if _, ok := mc.mutation.DeletedAt(); !ok {
		return &ValidationError{Name: "deleted_at", err: errors.New(`ent: missing required field "Message.deleted_at"`)}
	}
	if len(mc.mutation.OwnerIDs()) == 0 {
		return &ValidationError{Name: "owner", err: errors.New(`ent: missing required edge "Message.owner"`)}
	}
	if len(mc.mutation.ChatIDs()) == 0 {
		return &ValidationError{Name: "chat", err: errors.New(`ent: missing required edge "Message.chat"`)}
	}
	return nil
}

func (mc *MessageCreate) sqlSave(ctx context.Context) (*Message, error) {
	if err := mc.check(); err != nil {
		return nil, err
	}
	_node, _spec := mc.createSpec()
	if err := sqlgraph.CreateNode(ctx, mc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	mc.mutation.id = &_node.ID
	mc.mutation.done = true
	return _node, nil
}

func (mc *MessageCreate) createSpec() (*Message, *sqlgraph.CreateSpec) {
	var (
		_node = &Message{config: mc.config}
		_spec = sqlgraph.NewCreateSpec(message.Table, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	)
	if id, ok := mc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := mc.mutation.Platform(); ok {
		_spec.SetField(message.FieldPlatform, field.TypeString, value)
		_node.Platform = value
	}
	if value, ok := mc.mutation.PlatformMessageID(); ok {
		_spec.SetField(message.FieldPlatformMessageID, field.TypeString, value)
		_node.PlatformMessageID = value
	}
	if value, ok := mc.mutation.FromID(); ok {
		_spec.SetField(message.FieldFromID, field.TypeString, value)
		_node.FromID = value
	}
	if value, ok := mc.mutation.FromName(); ok {
		_spec.SetField(message.FieldFromName, field.TypeString, value)
		_node.FromName = value
	}
	if value, ok := mc.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := mc.mutation.IsReply(); ok {
		_spec.SetField(message.FieldIsReply, field.TypeBool, value)
		_node.IsReply = value
	}
	if value, ok := mc.mutation.ReplyToID(); ok {
		_spec.SetField(message.FieldReplyToID, field.TypeString, value)
		_node.ReplyToID = value
	}
	if value, ok := mc.mutation.ReplyToName(); ok {
		_spec.SetField(message.FieldReplyToName, field.TypeString, value)
		_node.ReplyToName = value
	}
	if value, ok := mc.mutation.PlatformTimestamp(); ok {
		_spec.SetField(message.FieldPlatformTimestamp, field.TypeInt64, value)
		_node.PlatformTimestamp = value
	}
	if value, ok := mc.mutation.ContentVectorModel(); ok {
		_spec.SetField(message.FieldContentVectorModel, field.TypeString, value)
		_node.ContentVectorModel = value
	}
	if value, ok := mc.mutation.JiebaTokens(); ok {
		_spec.SetField(message.FieldJiebaTokens, field.TypeJSON, value)
		_node.JiebaTokens = value
	}
	if value, ok := mc.mutation.CreatedAt(); ok {
		_spec.SetField(message.FieldCreatedAt, field.TypeInt64, value)
		_node.CreatedAt = value
	}
	if value, ok := mc.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeInt64, value)
		_node.UpdatedAt = value
	}
	if value, ok := mc.mutation.DeletedAt(); ok {
		_spec.SetField(message.FieldDeletedAt, field.TypeInt64, value)
		_node.DeletedAt = value
	}
	if nodes := mc.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.OwnerAccountID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := mc.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.InChatID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// MessageCreateBulk is the builder for creating many Message entities in bulk.
type MessageCreateBulk struct {
	config
	err      error
	builders []*MessageCreate
}

// Save creates the Message entities in the database.
func (mcb *MessageCreateBulk) Save(ctx context.Context) ([]*Message, error) {
	if mcb.err != nil {
		return nil, mcb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(mcb.builders))
	nodes := make([]*Message, len(mcb.builders))
	mutators := make([]Mutator, len(mcb.builders))
	for i := range mcb.builders {
		func(i int, root context.Context) {
			builder := mcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*MessageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, mcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, mcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, mcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (mcb *MessageCreateBulk) SaveX(ctx context.Context) []*Message {
	v, err := mcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (mcb *MessageCreateBulk) Exec(ctx context.Context) error {
	_, err := mcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mcb *MessageCreateBulk) ExecX(ctx context.Context) {
	if err := mcb.Exec(ctx); err != nil {
		panic(err)
	}
}
