// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
)

// Message is the model entity for the Message schema.
type Message struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// OwnerAccountID holds the value of the "owner_account_id" field.
	OwnerAccountID uuid.UUID `json:"owner_account_id,omitempty"`
	// InChatID holds the value of the "in_chat_id" field.
	InChatID uuid.UUID `json:"in_chat_id,omitempty"`
	// Platform holds the value of the "platform" field.
	Platform string `json:"platform,omitempty"`
	// PlatformMessageID holds the value of the "platform_message_id" field.
	PlatformMessageID string `json:"platform_message_id,omitempty"`
	// FromID holds the value of the "from_id" field.
	FromID string `json:"from_id,omitempty"`
	// FromName holds the value of the "from_name" field.
	FromName string `json:"from_name,omitempty"`
	// Content holds the value of the "content" field.
	Content string `json:"content,omitempty"`
	// IsReply holds the value of the "is_reply" field.
	IsReply bool `json:"is_reply,omitempty"`
	// ReplyToID holds the value of the "reply_to_id" field.
	ReplyToID string `json:"reply_to_id,omitempty"`
	// ReplyToName holds the value of the "reply_to_name" field.
	ReplyToName string `json:"reply_to_name,omitempty"`
	// PlatformTimestamp holds the value of the "platform_timestamp" field.
	PlatformTimestamp int64 `json:"platform_timestamp,omitempty"`
	// ContentVectorModel holds the value of the "content_vector_model" field.
	ContentVectorModel string `json:"content_vector_model,omitempty"`
	// JiebaTokens holds the value of the "jieba_tokens" field.
	JiebaTokens []string `json:"jieba_tokens,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt int64 `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt int64 `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt int64 `json:"deleted_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the MessageQuery when eager-loading is set.
	Edges        MessageEdges `json:"edges"`
	selectValues sql.SelectValues
}

// MessageEdges holds the relations/edges for other nodes in the graph.
type MessageEdges struct {
	// Owner holds the value of the owner edge.
	Owner *Account `json:"owner,omitempty"`
	// Chat holds the value of the chat edge.
	Chat *Chat `json:"chat,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// OwnerOrErr returns the Owner value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) OwnerOrErr() (*Account, error) {
	if e.Owner != nil {
		return e.Owner, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: account.Label}
	}
	return nil, &NotLoadedError{edge: "owner"}
}

// ChatOrErr returns the Chat value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e MessageEdges) ChatOrErr() (*Chat, error) {
	if e.Chat != nil {
		return e.Chat, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: chat.Label}
	}
	return nil, &NotLoadedError{edge: "chat"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Message) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case message.FieldJiebaTokens:
			values[i] = new([]byte)
		case message.FieldIsReply:
			values[i] = new(sql.NullBool)
		case message.FieldPlatformTimestamp, message.FieldCreatedAt, message.FieldUpdatedAt, message.FieldDeletedAt:
			values[i] = new(sql.NullInt64)
		case message.FieldPlatform, message.FieldPlatformMessageID, message.FieldFromID, message.FieldFromName, message.FieldContent, message.FieldReplyToID, message.FieldReplyToName, message.FieldContentVectorModel:
			values[i] = new(sql.NullString)
		case message.FieldID, message.FieldOwnerAccountID, message.FieldInChatID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Message fields.
func (m *Message) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case message.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				m.ID = *value
			}
		case message.FieldOwnerAccountID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field owner_account_id", values[i])
			} else if value != nil {
				m.OwnerAccountID = *value
			}
		case message.FieldInChatID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field in_chat_id", values[i])
			} else if value != nil {
				m.InChatID = *value
			}
		case message.FieldPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform", values[i])
			} else if value.Valid {
				m.Platform = value.String
			}
		case message.FieldPlatformMessageID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_message_id", values[i])
			} else if value.Valid {
				m.PlatformMessageID = value.String
			}
		case message.FieldFromID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_id", values[i])
			} else if value.Valid {
				m.FromID = value.String
			}
		case message.FieldFromName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field from_name", values[i])
			} else if value.Valid {
				m.FromName = value.String
			}
		case message.FieldContent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content", values[i])
			} else if value.Valid {
				m.Content = value.String
			}
		case message.FieldIsReply:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_reply", values[i])
			} else if value.Valid {
				m.IsReply = value.Bool
			}
		case message.FieldReplyToID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reply_to_id", values[i])
			} else if value.Valid {
				m.ReplyToID = value.String
			}
		case message.FieldReplyToName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reply_to_name", values[i])
			} else if value.Valid {
				m.ReplyToName = value.String
			}
		case message.FieldPlatformTimestamp:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field platform_timestamp", values[i])
			} else if value.Valid {
				m.PlatformTimestamp = value.Int64
			}
		case message.FieldContentVectorModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field content_vector_model", values[i])
			} else if value.Valid {
				m.ContentVectorModel = value.String
			}
		case message.FieldJiebaTokens:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field jieba_tokens", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &m.JiebaTokens); err != nil {
					return fmt.Errorf("unmarshal field jieba_tokens: %w", err)
				}
			}
		case message.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				m.CreatedAt = value.Int64
			}
		case message.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				m.UpdatedAt = value.Int64
			}
		case message.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				m.DeletedAt = value.Int64
			}
		default:
			m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Message.
// This includes values selected through modifiers, order, etc.
func (m *Message) Value(name string) (ent.Value, error) {
	return m.selectValues.Get(name)
}

// QueryOwner queries the "owner" edge of the Message entity.
func (m *Message) QueryOwner() *AccountQuery {
	return NewMessageClient(m.config).QueryOwner(m)
}

// QueryChat queries the "chat" edge of the Message entity.
func (m *Message) QueryChat() *ChatQuery {
	return NewMessageClient(m.config).QueryChat(m)
}

// Update returns a builder for updating this Message.
// Note that you need to call Message.Unwrap() before calling this method if this Message
// was returned from a transaction, and the transaction was committed or rolled back.
func (m *Message) Update() *MessageUpdateOne {
	return NewMessageClient(m.config).UpdateOne(m)
}

// Unwrap unwraps the Message entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (m *Message) Unwrap() *Message {
	_tx, ok := m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Message is not a transactional entity")
	}
	m.config.driver = _tx.drv
	return m
}

// String implements the fmt.Stringer.
func (m *Message) String() string {
	var builder strings.Builder
	builder.WriteString("Message(")
	builder.WriteString(fmt.Sprintf("id=%v, ", m.ID))
	builder.WriteString("owner_account_id=")
	builder.WriteString(fmt.Sprintf("%v", m.OwnerAccountID))
	builder.WriteString(", ")
	builder.WriteString("in_chat_id=")
	builder.WriteString(fmt.Sprintf("%v", m.InChatID))
	builder.WriteString(", ")
	builder.WriteString("platform=")
	builder.WriteString(m.Platform)
	builder.WriteString(", ")
	builder.WriteString("platform_message_id=")
	builder.WriteString(m.PlatformMessageID)
	builder.WriteString(", ")
	builder.WriteString("from_id=")
	builder.WriteString(m.FromID)
	builder.WriteString(", ")
	builder.WriteString("from_name=")
	builder.WriteString(m.FromName)
	builder.WriteString(", ")
	builder.WriteString("content=")
	builder.WriteString(m.Content)
	builder.WriteString(", ")
	builder.WriteString("is_reply=")
	builder.WriteString(fmt.Sprintf("%v", m.IsReply))
	builder.WriteString(", ")
	builder.WriteString("reply_to_id=")
	builder.WriteString(m.ReplyToID)
	builder.WriteString(", ")
	builder.WriteString("reply_to_name=")
	builder.WriteString(m.ReplyToName)
	builder.WriteString(", ")
	builder.WriteString("platform_timestamp=")
	builder.WriteString(fmt.Sprintf("%v", m.PlatformTimestamp))
	builder.WriteString(", ")
	builder.WriteString("content_vector_model=")
	builder.WriteString(m.ContentVectorModel)
	builder.WriteString(", ")
	builder.WriteString("jieba_tokens=")
	builder.WriteString(fmt.Sprintf("%v", m.JiebaTokens))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(fmt.Sprintf("%v", m.CreatedAt))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(fmt.Sprintf("%v", m.UpdatedAt))
	builder.WriteString(", ")
	builder.WriteString("deleted_at=")
	builder.WriteString(fmt.Sprintf("%v", m.DeletedAt))
	builder.WriteByte(')')
	return builder.String()
}

// Messages is a parsable slice of Message.
type Messages []*Message
