// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
	"github.com/groupultra/telegram-search/ent/predicate"
)

// MessageUpdate is the builder for updating Message entities.
type MessageUpdate struct {
	config
	hooks    []Hook
	mutation *MessageMutation
}

// Where appends a list predicates to the MessageUpdate builder.
func (mu *MessageUpdate) Where(ps ...predicate.Message) *MessageUpdate {
	mu.mutation.Where(ps...)
	return mu
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (mu *MessageUpdate) SetOwnerAccountID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetOwnerAccountID(u)
	return mu
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableOwnerAccountID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetOwnerAccountID(*u)
	}
	return mu
}

// SetInChatID sets the "in_chat_id" field.
func (mu *MessageUpdate) SetInChatID(u uuid.UUID) *MessageUpdate {
	mu.mutation.SetInChatID(u)
	return mu
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableInChatID(u *uuid.UUID) *MessageUpdate {
	if u != nil {
		mu.SetInChatID(*u)
	}
	return mu
}

// SetPlatform sets the "platform" field.
func (mu *MessageUpdate) SetPlatform(s string) *MessageUpdate {
	mu.mutation.SetPlatform(s)
	return mu
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (mu *MessageUpdate) SetNillablePlatform(s *string) *MessageUpdate {
	if s != nil {
		mu.SetPlatform(*s)
	}
	return mu
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (mu *MessageUpdate) SetPlatformMessageID(s string) *MessageUpdate {
	mu.mutation.SetPlatformMessageID(s)
	return mu
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillablePlatformMessageID(s *string) *MessageUpdate {
	if s != nil {
		mu.SetPlatformMessageID(*s)
	}
	return mu
}

// SetFromID sets the "from_id" field.
func (mu *MessageUpdate) SetFromID(s string) *MessageUpdate {
	mu.mutation.SetFromID(s)
	return mu
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableFromID(s *string) *MessageUpdate {
	if s != nil {
		mu.SetFromID(*s)
	}
	return mu
}

// SetFromName sets the "from_name" field.
func (mu *MessageUpdate) SetFromName(s string) *MessageUpdate {
	mu.mutation.SetFromName(s)
	return mu
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableFromName(s *string) *MessageUpdate {
	if s != nil {
		mu.SetFromName(*s)
	}
	return mu
}

// SetContent sets the "content" field.
func (mu *MessageUpdate) SetContent(s string) *MessageUpdate {
	mu.mutation.SetContent(s)
	return mu
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableContent(s *string) *MessageUpdate {
	if s != nil {
		mu.SetContent(*s)
	}
	return mu
}

// SetIsReply sets the "is_reply" field.
func (mu *MessageUpdate) SetIsReply(b bool) *MessageUpdate {
	mu.mutation.SetIsReply(b)
	return mu
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableIsReply(b *bool) *MessageUpdate {
	if b != nil {
		mu.SetIsReply(*b)
	}
	return mu
}

// SetReplyToID sets the "reply_to_id" field.
func (mu *MessageUpdate) SetReplyToID(s string) *MessageUpdate {
	mu.mutation.SetReplyToID(s)
	return mu
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableReplyToID(s *string) *MessageUpdate {
	if s != nil {
		mu.SetReplyToID(*s)
	}
	return mu
}

// SetReplyToName sets the "reply_to_name" field.
func (mu *MessageUpdate) SetReplyToName(s string) *MessageUpdate {
	mu.mutation.SetReplyToName(s)
	return mu
}

// SetNillableReplyToName sets the "reply_to_name" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableReplyToName(s *string) *MessageUpdate {
	if s != nil {
		mu.SetReplyToName(*s)
	}
	return mu
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (mu *MessageUpdate) SetPlatformTimestamp(i int64) *MessageUpdate {
	mu.mutation.ResetPlatformTimestamp()
	mu.mutation.SetPlatformTimestamp(i)
	return mu
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (mu *MessageUpdate) SetNillablePlatformTimestamp(i *int64) *MessageUpdate {
	if i != nil {
		mu.SetPlatformTimestamp(*i)
	}
	return mu
}

// AddPlatformTimestamp adds i to the "platform_timestamp" field.
func (mu *MessageUpdate) AddPlatformTimestamp(i int64) *MessageUpdate {
	mu.mutation.AddPlatformTimestamp(i)
	return mu
}

// SetContentVectorModel sets the "content_vector_model" field.
func (mu *MessageUpdate) SetContentVectorModel(s string) *MessageUpdate {
	mu.mutation.SetContentVectorModel(s)
	return mu
}

// SetNillableContentVectorModel sets the "content_vector_model" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableContentVectorModel(s *string) *MessageUpdate {
	if s != nil {
		mu.SetContentVectorModel(*s)
	}
	return mu
}

// SetJiebaTokens sets the "jieba_tokens" field.
func (mu *MessageUpdate) SetJiebaTokens(s []string) *MessageUpdate {
	mu.mutation.SetJiebaTokens(s)
	return mu
}

// AppendJiebaTokens appends s to the "jieba_tokens" field.
func (mu *MessageUpdate) AppendJiebaTokens(s []string) *MessageUpdate {
	mu.mutation.AppendJiebaTokens(s)
	return mu
}

// ClearJiebaTokens clears the value of the "jieba_tokens" field.
func (mu *MessageUpdate) ClearJiebaTokens() *MessageUpdate {
	mu.mutation.ClearJiebaTokens()
	return mu
}

// SetUpdatedAt sets the "updated_at" field.
func (mu *MessageUpdate) SetUpdatedAt(i int64) *MessageUpdate {
	mu.mutation.ResetUpdatedAt()
	mu.mutation.SetUpdatedAt(i)
	return mu
}

// AddUpdatedAt adds i to the "updated_at" field.
func (mu *MessageUpdate) AddUpdatedAt(i int64) *MessageUpdate {
	mu.mutation.AddUpdatedAt(i)
	return mu
}

// SetDeletedAt sets the "deleted_at" field.
func (mu *MessageUpdate) SetDeletedAt(i int64) *MessageUpdate {
	mu.mutation.ResetDeletedAt()
	mu.mutation.SetDeletedAt(i)
	return mu
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (mu *MessageUpdate) SetNillableDeletedAt(i *int64) *MessageUpdate {
	if i != nil {
		mu.SetDeletedAt(*i)
	}
	return mu
}

// AddDeletedAt adds i to the "deleted_at" field.
func (mu *MessageUpdate) AddDeletedAt(i int64) *MessageUpdate {
	mu.mutation.AddDeletedAt(i)
	return mu
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (mu *MessageUpdate) SetOwnerID(id uuid.UUID) *MessageUpdate {
	mu.mutation.SetOwnerID(id)
	return mu
}

// SetOwner sets the "owner" edge to the Account entity.
func (mu *MessageUpdate) SetOwner(a *Account) *MessageUpdate {
	return mu.SetOwnerID(a.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (mu *MessageUpdate) SetChatID(id uuid.UUID) *MessageUpdate {
	mu.mutation.SetChatID(id)
	return mu
}

// SetChat sets the "chat" edge to the Chat entity.
func (mu *MessageUpdate) SetChat(c *Chat) *MessageUpdate {
	return mu.SetChatID(c.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (mu *MessageUpdate) Mutation() *MessageMutation {
	return mu.mutation
}

// ClearOwner clears the "owner" edge to the Account entity.
func (mu *MessageUpdate) ClearOwner() *MessageUpdate {
	mu.mutation.ClearOwner()
	return mu
}

// ClearChat clears the "chat" edge to the Chat entity.
func (mu *MessageUpdate) ClearChat() *MessageUpdate {
	mu.mutation.ClearChat()
	return mu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (mu *MessageUpdate) Save(ctx context.Context) (int, error) {
	mu.defaults()
	return withHooks(ctx, mu.sqlSave, mu.mutation, mu.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (mu *MessageUpdate) SaveX(ctx context.Context) int {
	affected, err := mu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (mu *MessageUpdate) Exec(ctx context.Context) error {
	_, err := mu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (mu *MessageUpdate) ExecX(ctx context.Context) {
	if err := mu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (mu *MessageUpdate) defaults() {
	if _, ok := mu.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		mu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (mu *MessageUpdate) check() error {
	if v, ok := mu.mutation.PlatformMessageID(); ok {
		if err := message.PlatformMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_message_id", err: fmt.Errorf(`ent: validator failed for field "Message.platform_message_id": %w`, err)}
		}
	}
	if mu.mutation.OwnerCleared() && len(mu.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.owner"`)
	}
	if mu.mutation.ChatCleared() && len(mu.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.chat"`)
	}
	return nil
}

func (mu *MessageUpdate) sqlSave(ctx context.Context) (n int, err error) {
	if err := mu.check(); err != nil {
		return n, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	if ps := mu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := mu.mutation.Platform(); ok {
		_spec.SetField(message.FieldPlatform, field.TypeString, value)
	}
	if value, ok := mu.mutation.PlatformMessageID(); ok {
		_spec.SetField(message.FieldPlatformMessageID, field.TypeString, value)
	}
	if value, ok := mu.mutation.FromID(); ok {
		_spec.SetField(message.FieldFromID, field.TypeString, value)
	}
	if value, ok := mu.mutation.FromName(); ok {
		_spec.SetField(message.FieldFromName, field.TypeString, value)
	}
	if value, ok := mu.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := mu.mutation.IsReply(); ok {
		_spec.SetField(message.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := mu.mutation.ReplyToID(); ok {
		_spec.SetField(message.FieldReplyToID, field.TypeString, value)
	}
	if value, ok := mu.mutation.ReplyToName(); ok {
		_spec.SetField(message.FieldReplyToName, field.TypeString, value)
	}
	if value, ok := mu.mutation.PlatformTimestamp(); ok {
		_spec.SetField(message.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(message.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.ContentVectorModel(); ok {
		_spec.SetField(message.FieldContentVectorModel, field.TypeString, value)
	}
	if value, ok := mu.mutation.JiebaTokens(); ok {
		_spec.SetField(message.FieldJiebaTokens, field.TypeJSON, value)
	}
	if value, ok := mu.mutation.AppendedJiebaTokens(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldJiebaTokens, value)
		})
	}
	if mu.mutation.JiebaTokensCleared() {
		_spec.ClearField(message.FieldJiebaTokens, field.TypeJSON)
	}
	if value, ok := mu.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(message.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.DeletedAt(); ok {
		_spec.SetField(message.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := mu.mutation.AddedDeletedAt(); ok {
		_spec.AddField(message.FieldDeletedAt, field.TypeInt64, value)
	}
	if mu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if mu.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := mu.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, mu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	mu.mutation.done = true
	return n, nil
}

// MessageUpdateOne is the builder for updating a single Message entity.
type MessageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *MessageMutation
}

// SetOwnerAccountID sets the "owner_account_id" field.
func (muo *MessageUpdateOne) SetOwnerAccountID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetOwnerAccountID(u)
	return muo
}

// SetNillableOwnerAccountID sets the "owner_account_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableOwnerAccountID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetOwnerAccountID(*u)
	}
	return muo
}

// SetInChatID sets the "in_chat_id" field.
func (muo *MessageUpdateOne) SetInChatID(u uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetInChatID(u)
	return muo
}

// SetNillableInChatID sets the "in_chat_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableInChatID(u *uuid.UUID) *MessageUpdateOne {
	if u != nil {
		muo.SetInChatID(*u)
	}
	return muo
}

// SetPlatform sets the "platform" field.
func (muo *MessageUpdateOne) SetPlatform(s string) *MessageUpdateOne {
	muo.mutation.SetPlatform(s)
	return muo
}

// SetNillablePlatform sets the "platform" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillablePlatform(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetPlatform(*s)
	}
	return muo
}

// SetPlatformMessageID sets the "platform_message_id" field.
func (muo *MessageUpdateOne) SetPlatformMessageID(s string) *MessageUpdateOne {
	muo.mutation.SetPlatformMessageID(s)
	return muo
}

// SetNillablePlatformMessageID sets the "platform_message_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillablePlatformMessageID(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetPlatformMessageID(*s)
	}
	return muo
}

// SetFromID sets the "from_id" field.
func (muo *MessageUpdateOne) SetFromID(s string) *MessageUpdateOne {
	muo.mutation.SetFromID(s)
	return muo
}

// SetNillableFromID sets the "from_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableFromID(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetFromID(*s)
	}
	return muo
}

// SetFromName sets the "from_name" field.
func (muo *MessageUpdateOne) SetFromName(s string) *MessageUpdateOne {
	muo.mutation.SetFromName(s)
	return muo
}

// SetNillableFromName sets the "from_name" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableFromName(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetFromName(*s)
	}
	return muo
}

// SetContent sets the "content" field.
func (muo *MessageUpdateOne) SetContent(s string) *MessageUpdateOne {
	muo.mutation.SetContent(s)
	return muo
}

// SetNillableContent sets the "content" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableContent(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetContent(*s)
	}
	return muo
}

// SetIsReply sets the "is_reply" field.
func (muo *MessageUpdateOne) SetIsReply(b bool) *MessageUpdateOne {
	muo.mutation.SetIsReply(b)
	return muo
}

// SetNillableIsReply sets the "is_reply" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableIsReply(b *bool) *MessageUpdateOne {
	if b != nil {
		muo.SetIsReply(*b)
	}
	return muo
}

// SetReplyToID sets the "reply_to_id" field.
func (muo *MessageUpdateOne) SetReplyToID(s string) *MessageUpdateOne {
	muo.mutation.SetReplyToID(s)
	return muo
}

// SetNillableReplyToID sets the "reply_to_id" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableReplyToID(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetReplyToID(*s)
	}
	return muo
}

// SetReplyToName sets the "reply_to_name" field.
func (muo *MessageUpdateOne) SetReplyToName(s string) *MessageUpdateOne {
	muo.mutation.SetReplyToName(s)
	return muo
}

// SetNillableReplyToName sets the "reply_to_name" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableReplyToName(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetReplyToName(*s)
	}
	return muo
}

// SetPlatformTimestamp sets the "platform_timestamp" field.
func (muo *MessageUpdateOne) SetPlatformTimestamp(i int64) *MessageUpdateOne {
	muo.mutation.ResetPlatformTimestamp()
	muo.mutation.SetPlatformTimestamp(i)
	return muo
}

// SetNillablePlatformTimestamp sets the "platform_timestamp" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillablePlatformTimestamp(i *int64) *MessageUpdateOne {
	if i != nil {
		muo.SetPlatformTimestamp(*i)
	}
	return muo
}

// AddPlatformTimestamp adds i to the "platform_timestamp" field.
func (muo *MessageUpdateOne) AddPlatformTimestamp(i int64) *MessageUpdateOne {
	muo.mutation.AddPlatformTimestamp(i)
	return muo
}

// SetContentVectorModel sets the "content_vector_model" field.
func (muo *MessageUpdateOne) SetContentVectorModel(s string) *MessageUpdateOne {
	muo.mutation.SetContentVectorModel(s)
	return muo
}

// SetNillableContentVectorModel sets the "content_vector_model" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableContentVectorModel(s *string) *MessageUpdateOne {
	if s != nil {
		muo.SetContentVectorModel(*s)
	}
	return muo
}

// SetJiebaTokens sets the "jieba_tokens" field.
func (muo *MessageUpdateOne) SetJiebaTokens(s []string) *MessageUpdateOne {
	muo.mutation.SetJiebaTokens(s)
	return muo
}

// AppendJiebaTokens appends s to the "jieba_tokens" field.
func (muo *MessageUpdateOne) AppendJiebaTokens(s []string) *MessageUpdateOne {
	muo.mutation.AppendJiebaTokens(s)
	return muo
}

// ClearJiebaTokens clears the value of the "jieba_tokens" field.
func (muo *MessageUpdateOne) ClearJiebaTokens() *MessageUpdateOne {
	muo.mutation.ClearJiebaTokens()
	return muo
}

// SetUpdatedAt sets the "updated_at" field.
func (muo *MessageUpdateOne) SetUpdatedAt(i int64) *MessageUpdateOne {
	muo.mutation.ResetUpdatedAt()
	muo.mutation.SetUpdatedAt(i)
	return muo
}

// AddUpdatedAt adds i to the "updated_at" field.
func (muo *MessageUpdateOne) AddUpdatedAt(i int64) *MessageUpdateOne {
	muo.mutation.AddUpdatedAt(i)
	return muo
}

// SetDeletedAt sets the "deleted_at" field.
func (muo *MessageUpdateOne) SetDeletedAt(i int64) *MessageUpdateOne {
	muo.mutation.ResetDeletedAt()
	muo.mutation.SetDeletedAt(i)
	return muo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (muo *MessageUpdateOne) SetNillableDeletedAt(i *int64) *MessageUpdateOne {
	if i != nil {
		muo.SetDeletedAt(*i)
	}
	return muo
}

// AddDeletedAt adds i to the "deleted_at" field.
func (muo *MessageUpdateOne) AddDeletedAt(i int64) *MessageUpdateOne {
	muo.mutation.AddDeletedAt(i)
	return muo
}

// SetOwnerID sets the "owner" edge to the Account entity by ID.
func (muo *MessageUpdateOne) SetOwnerID(id uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetOwnerID(id)
	return muo
}

// SetOwner sets the "owner" edge to the Account entity.
func (muo *MessageUpdateOne) SetOwner(a *Account) *MessageUpdateOne {
	return muo.SetOwnerID(a.ID)
}

// SetChatID sets the "chat" edge to the Chat entity by ID.
func (muo *MessageUpdateOne) SetChatID(id uuid.UUID) *MessageUpdateOne {
	muo.mutation.SetChatID(id)
	return muo
}

// SetChat sets the "chat" edge to the Chat entity.
func (muo *MessageUpdateOne) SetChat(c *Chat) *MessageUpdateOne {
	return muo.SetChatID(c.ID)
}

// Mutation returns the MessageMutation object of the builder.
func (muo *MessageUpdateOne) Mutation() *MessageMutation {
	return muo.mutation
}

// ClearOwner clears the "owner" edge to the Account entity.
func (muo *MessageUpdateOne) ClearOwner() *MessageUpdateOne {
	muo.mutation.ClearOwner()
	return muo
}

// ClearChat clears the "chat" edge to the Chat entity.
func (muo *MessageUpdateOne) ClearChat() *MessageUpdateOne {
	muo.mutation.ClearChat()
	return muo
}

// Where appends a list predicates to the MessageUpdate builder.
func (muo *MessageUpdateOne) Where(ps ...predicate.Message) *MessageUpdateOne {
	muo.mutation.Where(ps...)
	return muo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (muo *MessageUpdateOne) Select(field string, fields ...string) *MessageUpdateOne {
	muo.fields = append([]string{field}, fields...)
	return muo
}

// Save executes the query and returns the updated Message entity.
func (muo *MessageUpdateOne) Save(ctx context.Context) (*Message, error) {
	muo.defaults()
	return withHooks(ctx, muo.sqlSave, muo.mutation, muo.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (muo *MessageUpdateOne) SaveX(ctx context.Context) *Message {
	node, err := muo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (muo *MessageUpdateOne) Exec(ctx context.Context) error {
	_, err := muo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (muo *MessageUpdateOne) ExecX(ctx context.Context) {
	if err := muo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (muo *MessageUpdateOne) defaults() {
	if _, ok := muo.mutation.UpdatedAt(); !ok {
		v := message.UpdateDefaultUpdatedAt()
		muo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (muo *MessageUpdateOne) check() error {
	if v, ok := muo.mutation.PlatformMessageID(); ok {
		if err := message.PlatformMessageIDValidator(v); err != nil {
			return &ValidationError{Name: "platform_message_id", err: fmt.Errorf(`ent: validator failed for field "Message.platform_message_id": %w`, err)}
		}
	}
	if muo.mutation.OwnerCleared() && len(muo.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.owner"`)
	}
	if muo.mutation.ChatCleared() && len(muo.mutation.ChatIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Message.chat"`)
	}
	return nil
}

func (muo *MessageUpdateOne) sqlSave(ctx context.Context) (_node *Message, err error) {
	if err := muo.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(message.Table, message.Columns, sqlgraph.NewFieldSpec(message.FieldID, field.TypeUUID))
	id, ok := muo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Message.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := muo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, message.FieldID)
		for _, f := range fields {
			if !message.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != message.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := muo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := muo.mutation.Platform(); ok {
		_spec.SetField(message.FieldPlatform, field.TypeString, value)
	}
	if value, ok := muo.mutation.PlatformMessageID(); ok {
		_spec.SetField(message.FieldPlatformMessageID, field.TypeString, value)
	}
	if value, ok := muo.mutation.FromID(); ok {
		_spec.SetField(message.FieldFromID, field.TypeString, value)
	}
	if value, ok := muo.mutation.FromName(); ok {
		_spec.SetField(message.FieldFromName, field.TypeString, value)
	}
	if value, ok := muo.mutation.Content(); ok {
		_spec.SetField(message.FieldContent, field.TypeString, value)
	}
	if value, ok := muo.mutation.IsReply(); ok {
		_spec.SetField(message.FieldIsReply, field.TypeBool, value)
	}
	if value, ok := muo.mutation.ReplyToID(); ok {
		_spec.SetField(message.FieldReplyToID, field.TypeString, value)
	}
	if value, ok := muo.mutation.ReplyToName(); ok {
		_spec.SetField(message.FieldReplyToName, field.TypeString, value)
	}
	if value, ok := muo.mutation.PlatformTimestamp(); ok {
		_spec.SetField(message.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedPlatformTimestamp(); ok {
		_spec.AddField(message.FieldPlatformTimestamp, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.ContentVectorModel(); ok {
		_spec.SetField(message.FieldContentVectorModel, field.TypeString, value)
	}
	if value, ok := muo.mutation.JiebaTokens(); ok {
		_spec.SetField(message.FieldJiebaTokens, field.TypeJSON, value)
	}
	if value, ok := muo.mutation.AppendedJiebaTokens(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, message.FieldJiebaTokens, value)
		})
	}
	if muo.mutation.JiebaTokensCleared() {
		_spec.ClearField(message.FieldJiebaTokens, field.TypeJSON)
	}
	if value, ok := muo.mutation.UpdatedAt(); ok {
		_spec.SetField(message.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedUpdatedAt(); ok {
		_spec.AddField(message.FieldUpdatedAt, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.DeletedAt(); ok {
		_spec.SetField(message.FieldDeletedAt, field.TypeInt64, value)
	}
	if value, ok := muo.mutation.AddedDeletedAt(); ok {
		_spec.AddField(message.FieldDeletedAt, field.TypeInt64, value)
	}
	if muo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.OwnerTable,
			Columns: []string{message.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if muo.mutation.ChatCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := muo.mutation.ChatIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   message.ChatTable,
			Columns: []string{message.ChatColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(chat.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Message{config: muo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, muo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{message.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	muo.mutation.done = true
	return _node, nil
}
