// Code generated by ent, DO NOT EDIT.

package ent

import (
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/account"
	"github.com/groupultra/telegram-search/ent/chat"
	"github.com/groupultra/telegram-search/ent/message"
	"github.com/groupultra/telegram-search/ent/schema"
	"github.com/groupultra/telegram-search/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	accountFields := schema.Account{}.Fields()
	_ = accountFields
	// accountDescPhone is the schema descriptor for phone field.
	accountDescPhone := accountFields[1].Descriptor()
	// account.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	account.PhoneValidator = accountDescPhone.Validators[0].(func(string) error)
	// accountDescSessionData is the schema descriptor for session_data field.
	accountDescSessionData := accountFields[2].Descriptor()
	// account.DefaultSessionData holds the default value on creation for the session_data field.
	account.DefaultSessionData = accountDescSessionData.Default.(string)
	// accountDescPts is the schema descriptor for pts field.
	accountDescPts := accountFields[4].Descriptor()
	// account.DefaultPts holds the default value on creation for the pts field.
	account.DefaultPts = accountDescPts.Default.(int)
	// accountDescQts is the schema descriptor for qts field.
	accountDescQts := accountFields[5].Descriptor()
	// account.DefaultQts holds the default value on creation for the qts field.
	account.DefaultQts = accountDescQts.Default.(int)
	// accountDescSeq is the schema descriptor for seq field.
	accountDescSeq := accountFields[6].Descriptor()
	// account.DefaultSeq holds the default value on creation for the seq field.
	account.DefaultSeq = accountDescSeq.Default.(int)
	// accountDescDate is the schema descriptor for date field.
	accountDescDate := accountFields[7].Descriptor()
	// account.DefaultDate holds the default value on creation for the date field.
	account.DefaultDate = accountDescDate.Default.(int)
	// accountDescLastSyncAt is the schema descriptor for last_sync_at field.
	accountDescLastSyncAt := accountFields[8].Descriptor()
	// account.DefaultLastSyncAt holds the default value on creation for the last_sync_at field.
	account.DefaultLastSyncAt = accountDescLastSyncAt.Default.(int64)
	// accountDescCreatedAt is the schema descriptor for created_at field.
	accountDescCreatedAt := accountFields[9].Descriptor()
	// account.DefaultCreatedAt holds the default value on creation for the created_at field.
	account.DefaultCreatedAt = accountDescCreatedAt.Default.(func() int64)
	// accountDescUpdatedAt is the schema descriptor for updated_at field.
	accountDescUpdatedAt := accountFields[10].Descriptor()
	// account.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	account.DefaultUpdatedAt = accountDescUpdatedAt.Default.(func() int64)
	// account.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	account.UpdateDefaultUpdatedAt = accountDescUpdatedAt.UpdateDefault.(func() int64)
	// accountDescID is the schema descriptor for id field.
	accountDescID := accountFields[0].Descriptor()
	// account.DefaultID holds the default value on creation for the id field.
	account.DefaultID = accountDescID.Default.(func() uuid.UUID)
	chatFields := schema.Chat{}.Fields()
	_ = chatFields
	// chatDescPlatform is the schema descriptor for platform field.
	chatDescPlatform := chatFields[2].Descriptor()
	// chat.DefaultPlatform holds the default value on creation for the platform field.
	chat.DefaultPlatform = chatDescPlatform.Default.(string)
	// chatDescChatID is the schema descriptor for chat_id field.
	chatDescChatID := chatFields[3].Descriptor()
	// chat.ChatIDValidator is a validator for the "chat_id" field. It is called by the builders before save.
	chat.ChatIDValidator = chatDescChatID.Validators[0].(func(string) error)
	// chatDescChatName is the schema descriptor for chat_name field.
	chatDescChatName := chatFields[4].Descriptor()
	// chat.DefaultChatName holds the default value on creation for the chat_name field.
	chat.DefaultChatName = chatDescChatName.Default.(string)
	// chatDescChatType is the schema descriptor for chat_type field.
	chatDescChatType := chatFields[5].Descriptor()
	// chat.DefaultChatType holds the default value on creation for the chat_type field.
	chat.DefaultChatType = chatDescChatType.Default.(string)
	// chatDescNote is the schema descriptor for note field.
	chatDescNote := chatFields[7].Descriptor()
	// chat.DefaultNote holds the default value on creation for the note field.
	chat.DefaultNote = chatDescNote.Default.(string)
	// chatDescCreatedAt is the schema descriptor for created_at field.
	chatDescCreatedAt := chatFields[8].Descriptor()
	// chat.DefaultCreatedAt holds the default value on creation for the created_at field.
	chat.DefaultCreatedAt = chatDescCreatedAt.Default.(func() int64)
	// chatDescUpdatedAt is the schema descriptor for updated_at field.
	chatDescUpdatedAt := chatFields[9].Descriptor()
	// chat.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	chat.DefaultUpdatedAt = chatDescUpdatedAt.Default.(func() int64)
	// chat.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	chat.UpdateDefaultUpdatedAt = chatDescUpdatedAt.UpdateDefault.(func() int64)
	// chatDescID is the schema descriptor for id field.
	chatDescID := chatFields[0].Descriptor()
	// chat.DefaultID holds the default value on creation for the id field.
	chat.DefaultID = chatDescID.Default.(func() uuid.UUID)
	messageFields := schema.Message{}.Fields()
	_ = messageFields
	// messageDescPlatform is the schema descriptor for platform field.
	messageDescPlatform := messageFields[3].Descriptor()
	// message.DefaultPlatform holds the default value on creation for the platform field.
	message.DefaultPlatform = messageDescPlatform.Default.(string)
	// messageDescPlatformMessageID is the schema descriptor for platform_message_id field.
	messageDescPlatformMessageID := messageFields[4].Descriptor()
	// message.PlatformMessageIDValidator is a validator for the "platform_message_id" field. It is called by the builders before save.
	message.PlatformMessageIDValidator = messageDescPlatformMessageID.Validators[0].(func(string) error)
	// messageDescFromID is the schema descriptor for from_id field.
	messageDescFromID := messageFields[5].Descriptor()
	// message.DefaultFromID holds the default value on creation for the from_id field.
	message.DefaultFromID = messageDescFromID.Default.(string)
	// messageDescFromName is the schema descriptor for from_name field.
	messageDescFromName := messageFields[6].Descriptor()
	// message.DefaultFromName holds the default value on creation for the from_name field.
	message.DefaultFromName = messageDescFromName.Default.(string)
	// messageDescContent is the schema descriptor for content field.
	messageDescContent := messageFields[7].Descriptor()
	// message.DefaultContent holds the default value on creation for the content field.
	message.DefaultContent = messageDescContent.Default.(string)
	// messageDescIsReply is the schema descriptor for is_reply field.
	messageDescIsReply := messageFields[8].Descriptor()
	// message.DefaultIsReply holds the default value on creation for the is_reply field.
	message.DefaultIsReply = messageDescIsReply.Default.(bool)
	// messageDescReplyToID is the schema descriptor for reply_to_id field.
	messageDescReplyToID := messageFields[9].Descriptor()
	// message.DefaultReplyToID holds the default value on creation for the reply_to_id field.
	message.DefaultReplyToID = messageDescReplyToID.Default.(string)
	// messageDescReplyToName is the schema descriptor for reply_to_name field.
	messageDescReplyToName := messageFields[10].Descriptor()
	// message.DefaultReplyToName holds the default value on creation for the reply_to_name field.
	message.DefaultReplyToName = messageDescReplyToName.Default.(string)
	// messageDescPlatformTimestamp is the schema descriptor for platform_timestamp field.
	messageDescPlatformTimestamp := messageFields[11].Descriptor()
	// message.DefaultPlatformTimestamp holds the default value on creation for the platform_timestamp field.
	message.DefaultPlatformTimestamp = messageDescPlatformTimestamp.Default.(int64)
	// messageDescContentVectorModel is the schema descriptor for content_vector_model field.
	messageDescContentVectorModel := messageFields[12].Descriptor()
	// message.DefaultContentVectorModel holds the default value on creation for the content_vector_model field.
	message.DefaultContentVectorModel = messageDescContentVectorModel.Default.(string)
	// messageDescCreatedAt is the schema descriptor for created_at field.
	messageDescCreatedAt := messageFields[14].Descriptor()
	// message.DefaultCreatedAt holds the default value on creation for the created_at field.
	message.DefaultCreatedAt = messageDescCreatedAt.Default.(func() int64)
	// messageDescUpdatedAt is the schema descriptor for updated_at field.
	messageDescUpdatedAt := messageFields[15].Descriptor()
	// message.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	message.DefaultUpdatedAt = messageDescUpdatedAt.Default.(func() int64)
	// message.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	message.UpdateDefaultUpdatedAt = messageDescUpdatedAt.UpdateDefault.(func() int64)
	// messageDescDeletedAt is the schema descriptor for deleted_at field.
	messageDescDeletedAt := messageFields[16].Descriptor()
	// message.DefaultDeletedAt holds the default value on creation for the deleted_at field.
	message.DefaultDeletedAt = messageDescDeletedAt.Default.(int64)
	// messageDescID is the schema descriptor for id field.
	messageDescID := messageFields[0].Descriptor()
	// message.DefaultID holds the default value on creation for the id field.
	message.DefaultID = messageDescID.Default.(func() uuid.UUID)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescTelegramID is the schema descriptor for telegram_id field.
	userDescTelegramID := userFields[1].Descriptor()
	// user.TelegramIDValidator is a validator for the "telegram_id" field. It is called by the builders before save.
	user.TelegramIDValidator = userDescTelegramID.Validators[0].(func(string) error)
	// userDescUsername is the schema descriptor for username field.
	userDescUsername := userFields[2].Descriptor()
	// user.DefaultUsername holds the default value on creation for the username field.
	user.DefaultUsername = userDescUsername.Default.(string)
	// userDescFirstName is the schema descriptor for first_name field.
	userDescFirstName := userFields[3].Descriptor()
	// user.DefaultFirstName holds the default value on creation for the first_name field.
	user.DefaultFirstName = userDescFirstName.Default.(string)
	// userDescLastName is the schema descriptor for last_name field.
	userDescLastName := userFields[4].Descriptor()
	// user.DefaultLastName holds the default value on creation for the last_name field.
	user.DefaultLastName = userDescLastName.Default.(string)
	// userDescIsBot is the schema descriptor for is_bot field.
	userDescIsBot := userFields[5].Descriptor()
	// user.DefaultIsBot holds the default value on creation for the is_bot field.
	user.DefaultIsBot = userDescIsBot.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[6].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() int64)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userFields[7].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() int64)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() int64)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}
