// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// AccountsColumns holds the columns for the "accounts" table.
	AccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "phone", Type: field.TypeString, Unique: true},
		{Name: "session_data", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "settings", Type: field.TypeJSON, Nullable: true},
		{Name: "pts", Type: field.TypeInt, Default: 0},
		{Name: "qts", Type: field.TypeInt, Default: 0},
		{Name: "seq", Type: field.TypeInt, Default: 0},
		{Name: "date", Type: field.TypeInt, Default: 0},
		{Name: "last_sync_at", Type: field.TypeInt64, Default: 0},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// AccountsTable holds the schema information for the "accounts" table.
	AccountsTable = &schema.Table{
		Name:       "accounts",
		Columns:    AccountsColumns,
		PrimaryKey: []*schema.Column{AccountsColumns[0]},
	}
	// ChatsColumns holds the columns for the "chats" table.
	ChatsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "platform", Type: field.TypeString, Default: "telegram"},
		{Name: "chat_id", Type: field.TypeString},
		{Name: "chat_name", Type: field.TypeString, Default: ""},
		{Name: "chat_type", Type: field.TypeString, Default: "group"},
		{Name: "chat_username", Type: field.TypeString, Nullable: true},
		{Name: "note", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "owner_account_id", Type: field.TypeUUID},
	}
	// ChatsTable holds the schema information for the "chats" table.
	ChatsTable = &schema.Table{
		Name:       "chats",
		Columns:    ChatsColumns,
		PrimaryKey: []*schema.Column{ChatsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "chats_accounts_chats",
				Columns:    []*schema.Column{ChatsColumns[9]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "chat_owner_account_id_chat_id",
				Unique:  true,
				Columns: []*schema.Column{ChatsColumns[9], ChatsColumns[2]},
			},
		},
	}
	// MessagesColumns holds the columns for the "messages" table.
	MessagesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "platform", Type: field.TypeString, Default: "telegram"},
		{Name: "platform_message_id", Type: field.TypeString},
		{Name: "from_id", Type: field.TypeString, Default: ""},
		{Name: "from_name", Type: field.TypeString, Default: ""},
		{Name: "content", Type: field.TypeString, Size: 2147483647, Default: ""},
		{Name: "is_reply", Type: field.TypeBool, Default: false},
		{Name: "reply_to_id", Type: field.TypeString, Default: ""},
		{Name: "reply_to_name", Type: field.TypeString, Default: ""},
		{Name: "platform_timestamp", Type: field.TypeInt64, Default: 0},
		{Name: "content_vector_model", Type: field.TypeString, Default: ""},
		{Name: "jieba_tokens", Type: field.TypeJSON, Nullable: true},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
		{Name: "deleted_at", Type: field.TypeInt64, Default: 0},
		{Name: "owner_account_id", Type: field.TypeUUID},
		{Name: "in_chat_id", Type: field.TypeUUID},
	}
	// MessagesTable holds the schema information for the "messages" table.
	MessagesTable = &schema.Table{
		Name:       "messages",
		Columns:    MessagesColumns,
		PrimaryKey: []*schema.Column{MessagesColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "messages_accounts_messages",
				Columns:    []*schema.Column{MessagesColumns[15]},
				RefColumns: []*schema.Column{AccountsColumns[0]},
				OnDelete:   schema.NoAction,
			},
			{
				Symbol:     "messages_chats_messages",
				Columns:    []*schema.Column{MessagesColumns[16]},
				RefColumns: []*schema.Column{ChatsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
		Indexes: []*schema.Index{
			{
				Name:    "message_owner_account_id_in_chat_id_platform_message_id",
				Unique:  true,
				Columns: []*schema.Column{MessagesColumns[15], MessagesColumns[16], MessagesColumns[2]},
			},
			{
				Name:    "message_in_chat_id_platform_timestamp",
				Unique:  false,
				Columns: []*schema.Column{MessagesColumns[16], MessagesColumns[9]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "telegram_id", Type: field.TypeString},
		{Name: "username", Type: field.TypeString, Default: ""},
		{Name: "first_name", Type: field.TypeString, Default: ""},
		{Name: "last_name", Type: field.TypeString, Default: ""},
		{Name: "is_bot", Type: field.TypeBool, Default: false},
		{Name: "created_at", Type: field.TypeInt64},
		{Name: "updated_at", Type: field.TypeInt64},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_telegram_id",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		AccountsTable,
		ChatsTable,
		MessagesTable,
		UsersTable,
	}
)

func init() {
	ChatsTable.ForeignKeys[0].RefTable = AccountsTable
	MessagesTable.ForeignKeys[0].RefTable = AccountsTable
	MessagesTable.ForeignKeys[1].RefTable = ChatsTable
}
