// Code generated by ent, DO NOT EDIT.

package message

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the message type in the database.
	Label = "message"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerAccountID holds the string denoting the owner_account_id field in the database.
	FieldOwnerAccountID = "owner_account_id"
	// FieldInChatID holds the string denoting the in_chat_id field in the database.
	FieldInChatID = "in_chat_id"
	// FieldPlatform holds the string denoting the platform field in the database.
	FieldPlatform = "platform"
	// FieldPlatformMessageID holds the string denoting the platform_message_id field in the database.
	FieldPlatformMessageID = "platform_message_id"
	// FieldFromID holds the string denoting the from_id field in the database.
	FieldFromID = "from_id"
	// FieldFromName holds the string denoting the from_name field in the database.
	FieldFromName = "from_name"
	// FieldContent holds the string denoting the content field in the database.
	FieldContent = "content"
	// FieldIsReply holds the string denoting the is_reply field in the database.
	FieldIsReply = "is_reply"
	// FieldReplyToID holds the string denoting the reply_to_id field in the database.
	FieldReplyToID = "reply_to_id"
	// FieldReplyToName holds the string denoting the reply_to_name field in the database.
	FieldReplyToName = "reply_to_name"
	// FieldPlatformTimestamp holds the string denoting the platform_timestamp field in the database.
	FieldPlatformTimestamp = "platform_timestamp"
	// FieldContentVectorModel holds the string denoting the content_vector_model field in the database.
	FieldContentVectorModel = "content_vector_model"
	// FieldJiebaTokens holds the string denoting the jieba_tokens field in the database.
	FieldJiebaTokens = "jieba_tokens"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeChat holds the string denoting the chat edge name in mutations.
	EdgeChat = "chat"
	// Table holds the table name of the message in the database.
	Table = "messages"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "messages"
	// OwnerInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	OwnerInverseTable = "accounts"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_account_id"
	// ChatTable is the table that holds the chat relation/edge.
	ChatTable = "messages"
	// ChatInverseTable is the table name for the Chat entity.
	// It exists in this package in order to avoid circular dependency with the "chat" package.
	ChatInverseTable = "chats"
	// ChatColumn is the table column denoting the chat relation/edge.
	ChatColumn = "in_chat_id"
)

// Columns holds all SQL columns for message fields.
var Columns = []string{
	FieldID,
	FieldOwnerAccountID,
	FieldInChatID,
	FieldPlatform,
	FieldPlatformMessageID,
	FieldFromID,
	FieldFromName,
	FieldContent,
	FieldIsReply,
	FieldReplyToID,
	FieldReplyToName,
	FieldPlatformTimestamp,
	FieldContentVectorModel,
	FieldJiebaTokens,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultPlatform holds the default value on creation for the "platform" field.
	DefaultPlatform string
	// PlatformMessageIDValidator is a validator for the "platform_message_id" field. It is called by the builders before save.
	PlatformMessageIDValidator func(string) error
	// DefaultFromID holds the default value on creation for the "from_id" field.
	DefaultFromID string
	// DefaultFromName holds the default value on creation for the "from_name" field.
	DefaultFromName string
	// DefaultContent holds the default value on creation for the "content" field.
	DefaultContent string
	// DefaultIsReply holds the default value on creation for the "is_reply" field.
	DefaultIsReply bool
	// DefaultReplyToID holds the default value on creation for the "reply_to_id" field.
	DefaultReplyToID string
	// DefaultReplyToName holds the default value on creation for the "reply_to_name" field.
	DefaultReplyToName string
	// DefaultPlatformTimestamp holds the default value on creation for the "platform_timestamp" field.
	DefaultPlatformTimestamp int64
	// DefaultContentVectorModel holds the default value on creation for the "content_vector_model" field.
	DefaultContentVectorModel string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() int64
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() int64
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() int64
	// DefaultDeletedAt holds the default value on creation for the "deleted_at" field.
	DefaultDeletedAt int64
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Message queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerAccountID orders the results by the owner_account_id field.
func ByOwnerAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerAccountID, opts...).ToFunc()
}

// ByInChatID orders the results by the in_chat_id field.
func ByInChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInChatID, opts...).ToFunc()
}

// ByPlatform orders the results by the platform field.
func ByPlatform(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatform, opts...).ToFunc()
}

// ByPlatformMessageID orders the results by the platform_message_id field.
func ByPlatformMessageID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformMessageID, opts...).ToFunc()
}

// ByFromID orders the results by the from_id field.
func ByFromID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromID, opts...).ToFunc()
}

// ByFromName orders the results by the from_name field.
func ByFromName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFromName, opts...).ToFunc()
}

// ByContent orders the results by the content field.
func ByContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContent, opts...).ToFunc()
}

// ByIsReply orders the results by the is_reply field.
func ByIsReply(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsReply, opts...).ToFunc()
}

// ByReplyToID orders the results by the reply_to_id field.
func ByReplyToID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToID, opts...).ToFunc()
}

// ByReplyToName orders the results by the reply_to_name field.
func ByReplyToName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReplyToName, opts...).ToFunc()
}

// ByPlatformTimestamp orders the results by the platform_timestamp field.
func ByPlatformTimestamp(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlatformTimestamp, opts...).ToFunc()
}

// ByContentVectorModel orders the results by the content_vector_model field.
func ByContentVectorModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContentVectorModel, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByChatField orders the results by chat field.
func ByChatField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newChatStep(), sql.OrderByField(field, opts...))
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
	)
}
func newChatStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ChatInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, ChatTable, ChatColumn),
	)
}
