// Code generated by ent, DO NOT EDIT.

package message

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/groupultra/telegram-search/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldID, id))
}

// OwnerAccountID applies equality check predicate on the "owner_account_id" field. It's identical to OwnerAccountIDEQ.
func OwnerAccountID(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldOwnerAccountID, v))
}

// InChatID applies equality check predicate on the "in_chat_id" field. It's identical to InChatIDEQ.
func InChatID(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldInChatID, v))
}

// Platform applies equality check predicate on the "platform" field. It's identical to PlatformEQ.
func Platform(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatform, v))
}

// PlatformMessageID applies equality check predicate on the "platform_message_id" field. It's identical to PlatformMessageIDEQ.
func PlatformMessageID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatformMessageID, v))
}

// FromID applies equality check predicate on the "from_id" field. It's identical to FromIDEQ.
func FromID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromID, v))
}

// FromName applies equality check predicate on the "from_name" field. It's identical to FromNameEQ.
func FromName(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromName, v))
}

// Content applies equality check predicate on the "content" field. It's identical to ContentEQ.
func Content(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// IsReply applies equality check predicate on the "is_reply" field. It's identical to IsReplyEQ.
func IsReply(v bool) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldIsReply, v))
}

// ReplyToID applies equality check predicate on the "reply_to_id" field. It's identical to ReplyToIDEQ.
func ReplyToID(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToID, v))
}

// ReplyToName applies equality check predicate on the "reply_to_name" field. It's identical to ReplyToNameEQ.
func ReplyToName(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToName, v))
}

// PlatformTimestamp applies equality check predicate on the "platform_timestamp" field. It's identical to PlatformTimestampEQ.
func PlatformTimestamp(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// ContentVectorModel applies equality check predicate on the "content_vector_model" field. It's identical to ContentVectorModelEQ.
func ContentVectorModel(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContentVectorModel, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldDeletedAt, v))
}

// OwnerAccountIDEQ applies the EQ predicate on the "owner_account_id" field.
func OwnerAccountIDEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDNEQ applies the NEQ predicate on the "owner_account_id" field.
func OwnerAccountIDNEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldOwnerAccountID, v))
}

// OwnerAccountIDIn applies the In predicate on the "owner_account_id" field.
func OwnerAccountIDIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldOwnerAccountID, vs...))
}

// OwnerAccountIDNotIn applies the NotIn predicate on the "owner_account_id" field.
func OwnerAccountIDNotIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldOwnerAccountID, vs...))
}

// InChatIDEQ applies the EQ predicate on the "in_chat_id" field.
func InChatIDEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldInChatID, v))
}

// InChatIDNEQ applies the NEQ predicate on the "in_chat_id" field.
func InChatIDNEQ(v uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldInChatID, v))
}

// InChatIDIn applies the In predicate on the "in_chat_id" field.
func InChatIDIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldInChatID, vs...))
}

// InChatIDNotIn applies the NotIn predicate on the "in_chat_id" field.
func InChatIDNotIn(vs ...uuid.UUID) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldInChatID, vs...))
}

// PlatformEQ applies the EQ predicate on the "platform" field.
func PlatformEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatform, v))
}

// PlatformNEQ applies the NEQ predicate on the "platform" field.
func PlatformNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldPlatform, v))
}

// PlatformIn applies the In predicate on the "platform" field.
func PlatformIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldPlatform, vs...))
}

// PlatformNotIn applies the NotIn predicate on the "platform" field.
func PlatformNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldPlatform, vs...))
}

// PlatformGT applies the GT predicate on the "platform" field.
func PlatformGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldPlatform, v))
}

// PlatformGTE applies the GTE predicate on the "platform" field.
func PlatformGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldPlatform, v))
}

// PlatformLT applies the LT predicate on the "platform" field.
func PlatformLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldPlatform, v))
}

// PlatformLTE applies the LTE predicate on the "platform" field.
func PlatformLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldPlatform, v))
}

// PlatformContains applies the Contains predicate on the "platform" field.
func PlatformContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldPlatform, v))
}

// PlatformHasPrefix applies the HasPrefix predicate on the "platform" field.
func PlatformHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldPlatform, v))
}

// PlatformHasSuffix applies the HasSuffix predicate on the "platform" field.
func PlatformHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldPlatform, v))
}

// PlatformEqualFold applies the EqualFold predicate on the "platform" field.
func PlatformEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldPlatform, v))
}

// PlatformContainsFold applies the ContainsFold predicate on the "platform" field.
func PlatformContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldPlatform, v))
}

// PlatformMessageIDEQ applies the EQ predicate on the "platform_message_id" field.
func PlatformMessageIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatformMessageID, v))
}

// PlatformMessageIDNEQ applies the NEQ predicate on the "platform_message_id" field.
func PlatformMessageIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldPlatformMessageID, v))
}

// PlatformMessageIDIn applies the In predicate on the "platform_message_id" field.
func PlatformMessageIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldPlatformMessageID, vs...))
}

// PlatformMessageIDNotIn applies the NotIn predicate on the "platform_message_id" field.
func PlatformMessageIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldPlatformMessageID, vs...))
}

// PlatformMessageIDGT applies the GT predicate on the "platform_message_id" field.
func PlatformMessageIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldPlatformMessageID, v))
}

// PlatformMessageIDGTE applies the GTE predicate on the "platform_message_id" field.
func PlatformMessageIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldPlatformMessageID, v))
}

// PlatformMessageIDLT applies the LT predicate on the "platform_message_id" field.
func PlatformMessageIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldPlatformMessageID, v))
}

// PlatformMessageIDLTE applies the LTE predicate on the "platform_message_id" field.
func PlatformMessageIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldPlatformMessageID, v))
}

// PlatformMessageIDContains applies the Contains predicate on the "platform_message_id" field.
func PlatformMessageIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldPlatformMessageID, v))
}

// PlatformMessageIDHasPrefix applies the HasPrefix predicate on the "platform_message_id" field.
func PlatformMessageIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldPlatformMessageID, v))
}

// PlatformMessageIDHasSuffix applies the HasSuffix predicate on the "platform_message_id" field.
func PlatformMessageIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldPlatformMessageID, v))
}

// PlatformMessageIDEqualFold applies the EqualFold predicate on the "platform_message_id" field.
func PlatformMessageIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldPlatformMessageID, v))
}

// PlatformMessageIDContainsFold applies the ContainsFold predicate on the "platform_message_id" field.
func PlatformMessageIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldPlatformMessageID, v))
}

// FromIDEQ applies the EQ predicate on the "from_id" field.
func FromIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromID, v))
}

// FromIDNEQ applies the NEQ predicate on the "from_id" field.
func FromIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldFromID, v))
}

// FromIDIn applies the In predicate on the "from_id" field.
func FromIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldFromID, vs...))
}

// FromIDNotIn applies the NotIn predicate on the "from_id" field.
func FromIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldFromID, vs...))
}

// FromIDGT applies the GT predicate on the "from_id" field.
func FromIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldFromID, v))
}

// FromIDGTE applies the GTE predicate on the "from_id" field.
func FromIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldFromID, v))
}

// FromIDLT applies the LT predicate on the "from_id" field.
func FromIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldFromID, v))
}

// FromIDLTE applies the LTE predicate on the "from_id" field.
func FromIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldFromID, v))
}

// FromIDContains applies the Contains predicate on the "from_id" field.
func FromIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldFromID, v))
}

// FromIDHasPrefix applies the HasPrefix predicate on the "from_id" field.
func FromIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldFromID, v))
}

// FromIDHasSuffix applies the HasSuffix predicate on the "from_id" field.
func FromIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldFromID, v))
}

// FromIDEqualFold applies the EqualFold predicate on the "from_id" field.
func FromIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldFromID, v))
}

// FromIDContainsFold applies the ContainsFold predicate on the "from_id" field.
func FromIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldFromID, v))
}

// FromNameEQ applies the EQ predicate on the "from_name" field.
func FromNameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldFromName, v))
}

// FromNameNEQ applies the NEQ predicate on the "from_name" field.
func FromNameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldFromName, v))
}

// FromNameIn applies the In predicate on the "from_name" field.
func FromNameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldFromName, vs...))
}

// FromNameNotIn applies the NotIn predicate on the "from_name" field.
func FromNameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldFromName, vs...))
}

// FromNameGT applies the GT predicate on the "from_name" field.
func FromNameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldFromName, v))
}

// FromNameGTE applies the GTE predicate on the "from_name" field.
func FromNameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldFromName, v))
}

// FromNameLT applies the LT predicate on the "from_name" field.
func FromNameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldFromName, v))
}

// FromNameLTE applies the LTE predicate on the "from_name" field.
func FromNameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldFromName, v))
}

// FromNameContains applies the Contains predicate on the "from_name" field.
func FromNameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldFromName, v))
}

// FromNameHasPrefix applies the HasPrefix predicate on the "from_name" field.
func FromNameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldFromName, v))
}

// FromNameHasSuffix applies the HasSuffix predicate on the "from_name" field.
func FromNameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldFromName, v))
}

// FromNameEqualFold applies the EqualFold predicate on the "from_name" field.
func FromNameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldFromName, v))
}

// FromNameContainsFold applies the ContainsFold predicate on the "from_name" field.
func FromNameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldFromName, v))
}

// ContentEQ applies the EQ predicate on the "content" field.
func ContentEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContent, v))
}

// ContentNEQ applies the NEQ predicate on the "content" field.
func ContentNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldContent, v))
}

// ContentIn applies the In predicate on the "content" field.
func ContentIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldContent, vs...))
}

// ContentNotIn applies the NotIn predicate on the "content" field.
func ContentNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldContent, vs...))
}

// ContentGT applies the GT predicate on the "content" field.
func ContentGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldContent, v))
}

// ContentGTE applies the GTE predicate on the "content" field.
func ContentGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldContent, v))
}

// ContentLT applies the LT predicate on the "content" field.
func ContentLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldContent, v))
}

// ContentLTE applies the LTE predicate on the "content" field.
func ContentLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldContent, v))
}

// ContentContains applies the Contains predicate on the "content" field.
func ContentContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldContent, v))
}

// ContentHasPrefix applies the HasPrefix predicate on the "content" field.
func ContentHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldContent, v))
}

// ContentHasSuffix applies the HasSuffix predicate on the "content" field.
func ContentHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldContent, v))
}

// ContentEqualFold applies the EqualFold predicate on the "content" field.
func ContentEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldContent, v))
}

// ContentContainsFold applies the ContainsFold predicate on the "content" field.
func ContentContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldContent, v))
}

// IsReplyEQ applies the EQ predicate on the "is_reply" field.
func IsReplyEQ(v bool) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldIsReply, v))
}

// IsReplyNEQ applies the NEQ predicate on the "is_reply" field.
func IsReplyNEQ(v bool) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldIsReply, v))
}

// ReplyToIDEQ applies the EQ predicate on the "reply_to_id" field.
func ReplyToIDEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToID, v))
}

// ReplyToIDNEQ applies the NEQ predicate on the "reply_to_id" field.
func ReplyToIDNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReplyToID, v))
}

// ReplyToIDIn applies the In predicate on the "reply_to_id" field.
func ReplyToIDIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReplyToID, vs...))
}

// ReplyToIDNotIn applies the NotIn predicate on the "reply_to_id" field.
func ReplyToIDNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReplyToID, vs...))
}

// ReplyToIDGT applies the GT predicate on the "reply_to_id" field.
func ReplyToIDGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReplyToID, v))
}

// ReplyToIDGTE applies the GTE predicate on the "reply_to_id" field.
func ReplyToIDGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReplyToID, v))
}

// ReplyToIDLT applies the LT predicate on the "reply_to_id" field.
func ReplyToIDLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReplyToID, v))
}

// ReplyToIDLTE applies the LTE predicate on the "reply_to_id" field.
func ReplyToIDLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReplyToID, v))
}

// ReplyToIDContains applies the Contains predicate on the "reply_to_id" field.
func ReplyToIDContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldReplyToID, v))
}

// ReplyToIDHasPrefix applies the HasPrefix predicate on the "reply_to_id" field.
func ReplyToIDHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldReplyToID, v))
}

// ReplyToIDHasSuffix applies the HasSuffix predicate on the "reply_to_id" field.
func ReplyToIDHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldReplyToID, v))
}

// ReplyToIDEqualFold applies the EqualFold predicate on the "reply_to_id" field.
func ReplyToIDEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldReplyToID, v))
}

// ReplyToIDContainsFold applies the ContainsFold predicate on the "reply_to_id" field.
func ReplyToIDContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldReplyToID, v))
}

// ReplyToNameEQ applies the EQ predicate on the "reply_to_name" field.
func ReplyToNameEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldReplyToName, v))
}

// ReplyToNameNEQ applies the NEQ predicate on the "reply_to_name" field.
func ReplyToNameNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldReplyToName, v))
}

// ReplyToNameIn applies the In predicate on the "reply_to_name" field.
func ReplyToNameIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldReplyToName, vs...))
}

// ReplyToNameNotIn applies the NotIn predicate on the "reply_to_name" field.
func ReplyToNameNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldReplyToName, vs...))
}

// ReplyToNameGT applies the GT predicate on the "reply_to_name" field.
func ReplyToNameGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldReplyToName, v))
}

// ReplyToNameGTE applies the GTE predicate on the "reply_to_name" field.
func ReplyToNameGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldReplyToName, v))
}

// ReplyToNameLT applies the LT predicate on the "reply_to_name" field.
func ReplyToNameLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldReplyToName, v))
}

// ReplyToNameLTE applies the LTE predicate on the "reply_to_name" field.
func ReplyToNameLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldReplyToName, v))
}

// ReplyToNameContains applies the Contains predicate on the "reply_to_name" field.
func ReplyToNameContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldReplyToName, v))
}

// ReplyToNameHasPrefix applies the HasPrefix predicate on the "reply_to_name" field.
func ReplyToNameHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldReplyToName, v))
}

// ReplyToNameHasSuffix applies the HasSuffix predicate on the "reply_to_name" field.
func ReplyToNameHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldReplyToName, v))
}

// ReplyToNameEqualFold applies the EqualFold predicate on the "reply_to_name" field.
func ReplyToNameEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldReplyToName, v))
}

// ReplyToNameContainsFold applies the ContainsFold predicate on the "reply_to_name" field.
func ReplyToNameContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldReplyToName, v))
}

// PlatformTimestampEQ applies the EQ predicate on the "platform_timestamp" field.
func PlatformTimestampEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampNEQ applies the NEQ predicate on the "platform_timestamp" field.
func PlatformTimestampNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldPlatformTimestamp, v))
}

// PlatformTimestampIn applies the In predicate on the "platform_timestamp" field.
func PlatformTimestampIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampNotIn applies the NotIn predicate on the "platform_timestamp" field.
func PlatformTimestampNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldPlatformTimestamp, vs...))
}

// PlatformTimestampGT applies the GT predicate on the "platform_timestamp" field.
func PlatformTimestampGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldPlatformTimestamp, v))
}

// PlatformTimestampGTE applies the GTE predicate on the "platform_timestamp" field.
func PlatformTimestampGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldPlatformTimestamp, v))
}

// PlatformTimestampLT applies the LT predicate on the "platform_timestamp" field.
func PlatformTimestampLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldPlatformTimestamp, v))
}

// PlatformTimestampLTE applies the LTE predicate on the "platform_timestamp" field.
func PlatformTimestampLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldPlatformTimestamp, v))
}

// ContentVectorModelEQ applies the EQ predicate on the "content_vector_model" field.
func ContentVectorModelEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldContentVectorModel, v))
}

// ContentVectorModelNEQ applies the NEQ predicate on the "content_vector_model" field.
func ContentVectorModelNEQ(v string) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldContentVectorModel, v))
}

// ContentVectorModelIn applies the In predicate on the "content_vector_model" field.
func ContentVectorModelIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldContentVectorModel, vs...))
}

// ContentVectorModelNotIn applies the NotIn predicate on the "content_vector_model" field.
func ContentVectorModelNotIn(vs ...string) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldContentVectorModel, vs...))
}

// ContentVectorModelGT applies the GT predicate on the "content_vector_model" field.
func ContentVectorModelGT(v string) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldContentVectorModel, v))
}

// ContentVectorModelGTE applies the GTE predicate on the "content_vector_model" field.
func ContentVectorModelGTE(v string) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldContentVectorModel, v))
}

// ContentVectorModelLT applies the LT predicate on the "content_vector_model" field.
func ContentVectorModelLT(v string) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldContentVectorModel, v))
}

// ContentVectorModelLTE applies the LTE predicate on the "content_vector_model" field.
func ContentVectorModelLTE(v string) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldContentVectorModel, v))
}

// ContentVectorModelContains applies the Contains predicate on the "content_vector_model" field.
func ContentVectorModelContains(v string) predicate.Message {
	return predicate.Message(sql.FieldContains(FieldContentVectorModel, v))
}

// ContentVectorModelHasPrefix applies the HasPrefix predicate on the "content_vector_model" field.
func ContentVectorModelHasPrefix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasPrefix(FieldContentVectorModel, v))
}

// ContentVectorModelHasSuffix applies the HasSuffix predicate on the "content_vector_model" field.
func ContentVectorModelHasSuffix(v string) predicate.Message {
	return predicate.Message(sql.FieldHasSuffix(FieldContentVectorModel, v))
}

// ContentVectorModelEqualFold applies the EqualFold predicate on the "content_vector_model" field.
func ContentVectorModelEqualFold(v string) predicate.Message {
	return predicate.Message(sql.FieldEqualFold(FieldContentVectorModel, v))
}

// ContentVectorModelContainsFold applies the ContainsFold predicate on the "content_vector_model" field.
func ContentVectorModelContainsFold(v string) predicate.Message {
	return predicate.Message(sql.FieldContainsFold(FieldContentVectorModel, v))
}

// JiebaTokensIsNil applies the IsNil predicate on the "jieba_tokens" field.
func JiebaTokensIsNil() predicate.Message {
	return predicate.Message(sql.FieldIsNull(FieldJiebaTokens))
}

// JiebaTokensNotNil applies the NotNil predicate on the "jieba_tokens" field.
func JiebaTokensNotNil() predicate.Message {
	return predicate.Message(sql.FieldNotNull(FieldJiebaTokens))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v int64) predicate.Message {
	return predicate.Message(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...int64) predicate.Message {
	return predicate.Message(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v int64) predicate.Message {
	return predicate.Message(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v int64) predicate.Message {
	return predicate.Message(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v int64) predicate.Message {
	return predicate.Message(sql.FieldLTE(FieldDeletedAt, v))
}

// HasOwner applies the HasEdge predicate on the "owner" edge.
func HasOwner() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, OwnerTable, OwnerColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasOwnerWith applies the HasEdge predicate on the "owner" edge with a given conditions (other predicates).
func HasOwnerWith(preds ...predicate.Account) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newOwnerStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasChat applies the HasEdge predicate on the "chat" edge.
func HasChat() predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ChatTable, ChatColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasChatWith applies the HasEdge predicate on the "chat" edge with a given conditions (other predicates).
func HasChatWith(preds ...predicate.Chat) predicate.Message {
	return predicate.Message(func(s *sql.Selector) {
		step := newChatStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Message) predicate.Message {
	return predicate.Message(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Message) predicate.Message {
	return predicate.Message(sql.NotPredicates(p))
}
